pt-plugins/PT-Plugin-Plus

- resource/sites/totheglory.im/browse.js
- resource/sites/totheglory.im/getSearchResult.js
- resource/sites/totheglory.im/parser/downloadURL.js
> fix: 修复TTG下载链接失效 (#120)

- resource/sites/hdbits.org/browse.js
- resource/sites/hdbits.org/config.json
- resource/sites/hdbits.org/details.js
- resource/sites/hdbits.org/getSearchResult.js
> feat: add support hdb site

- resource/sites/hdbits.org/config.json
- resource/sites/hdbits.org/getSearchResult.js
add torrent search tag and category support for hdb site
> feat: add torrent tag and category support for hdb site

- resource/sites/awesome-hd.me/config.json
- resource/sites/awesome-hd.me/getSearchResult.js
> feat: add support AHD site

- resource/sites/awesome-hd.me/getSearchResult.js
fix: imdb search issue and add torrent movie name for ahd site
> fix: imdb search issue and add torrent movie name for ahd site

- resource/sites/awesome-hd.me/config.json
- resource/sites/awesome-hd.me/getSearchResult.js
fix: tv torrent name display issue.
feat: add category,tag for ahd site.
> fixed tv torrent name display issue and add category,tag for ahd site

- resource/sites/beyond-hd.me/config.json
> fixed imdb search for BHD site

- resource/sites/filelist.ro/browse.js
- resource/sites/filelist.ro/config.json
- resource/sites/filelist.ro/details.js
- resource/sites/filelist.ro/getSearchResult.js
> feat: add filelist site

- resource/sites/chdbits.co/config.json
Fixed CHDBits IMDb number search issue.
> 修复CHDBits IMDb编号搜索无返回问题。

- resource/sites/nebulance.io/config.json
- resource/sites/nebulance.io/getSearchResult.js
- feat: 增加搜索支持，增加个人信息支持
受限于站点，不支持IMDb搜索。
> Add Nebulance full support.

- resource/schemas/AvistaZ/config.json
- resource/sites/awesome-hd.me/config.json
- resource/sites/nebulance.io/config.json
- resource/sites/passthepopcorn.me/config.json
- resource/sites/privatehd.to/config.json
- feat: 增加AHD、PTP和AvistaZ架构站点未读消息角标支持
- fix:
1. 将PHD站点介绍从欧美电视剧PT站修改为欧美影视
2. 修复NBL数字角标显示问题
> Add Message Badge Support for AHD, PTP，NBL and AvistaZ-based Trackers

- resource/sites/jpopsuki.eu/config.json
- feat: 修改JPopSuki未读消息角标提醒，原本只匹配Notifications
> Modified JPopSuki Message Badge Support

- resource/sites/filelist.ro/config.json
- resource/sites/karagarga.in/config.json
- resource/sites/karagarga.in/getSearchResult.js
- resource/sites/nebulance.io/config.json
- feat: 增加karagarga简单用户信息支持和搜索功能支持
- fix: 修复FileList做种体积显示为0的bug，修复Nebulance在支持站点列表中显示信息错误的问题
搜索结果显示的发布时间精确到年月日。时分统一显示为00:00，不是bug。这是因为KG的搜索结果页面并不提供精确到时分的信息，精确信息需要到种子详情页面获取，为了较少插件请求，故时分信息统一为00:00。
> 增加KG，并修复FL和NBL的两个小问题

- resource/sites/karagarga.in/config.json
- fix: 
- 修复原代码中KG体积在数字和字符之间没有空格时无法显示小数点之前数值的问题；
- 完善KG的标签。
> 修复KG用户数据在特殊情况下显示不正确的问题

- resource/sites/morethan.tv/config.json
- resource/sites/redacted.ch/config.json
- feat: 新增Morethan.tv支持
- fix: 修复Redacted做种超过一页时显示做种体积错误的问题
> 新增站点MTV，同时修复RED做种体积显示错误问题

- resource/sites/jpopsuki.eu/config.json
- resource/sites/jpopsuki.eu/getUserSeedingTorrents.js
- resource/sites/karagarga.in/config.json
- resource/sites/uhdbits.org/config.json
- resource/sites/uhdbits.org/getUserSeedingTorrents.js
- feat: 
- 增加KG做种数支持
- 增加KG做种体积支持
- 增加JpopSuki做种体积支持
- fix: 
- 修复UHDBits只显示第一页种子做种体积的问题
> 完善KG/JpopSuki/UHDBits做种体积显示

- resource/sites/dicmusic.club/config.json
- fix: 修复DICMusic站点做种体积显示不全的问题
> 修复海豚站做种体积显示不全的问题

- resource/sites/oppaiti.me/config.json
- resource/sites/pt.keepfrds.com/config.json
朋友主要是条幅没了。
Oppa是以前得适配有问题。抄了Red得修复
> fix 朋友获取新消息异常&Oppa信息获取

- resource/sites/uhdbits.org/getSearchResult.js
> fix 修复UHDBits搜索结果栏目错位

- resource/schemas/UNIT3D/config.json
- resource/sites/dxdhd.com/config.json
粗略支持，有新消息直接通过判断页面中有没有小点，有的话ptpp中也显示一个小点(~~只不过ptpp中的小点比较大~~)
由于需要显示具体数量的话，需要进入相应页面count,个人觉得比较繁琐并且不是很有必要(~~主要是我懒还有点不会写~~)
由于本人只有两个UNIT3D的站点(其中一个还有点问题)，所以建议测试一下
> UNIT3D 消息支持&DXDHD的一些修复(建议审核)

- resource/sites/dxdhd.com/config.json
> fix DXDHD搜索问题

- resource/sites/cinemageddon.net/getSearchResult.js
- fix: 修复CinemaGeddon搜索结果丢失第一行的问题。
> 修复CG搜索结果丢失第一行的问题

- resource/sites/npupt.com/config.json
fix: 修复 `NPUBits` 无法搜索与无法正确获得种子链接的Bug #146
加上了搜索分类，并格式化了json。
已进行一键下载、复制链接、搜索种子的测试。
> fix: 修复 `NPUBits` 无法搜索与无法正确获得种子链接的Bug

- resource/sites/cinemageddon.net/config.json
- feat:
- 增加CinemaGeddon credits支持；
- 增加CinemaGeddon 未读消息数角标显示。
> 增加CG魔力值及未读消息数支持

- resource/sites/pt.hdupt.com/config.json
- resource/sites/u2.dmhy.org/config.json
> U2 做种及下载信息增加

- resource/sites/hdchina.org/config.json
* ~~朋友~~
* 南洋
* 猫站
* * 萌猫
* 影客
* 搞清洁
* ~~HDC下载未活动显示为活动~~
* pth
> hdc 增加inactive的download判断

- resource/sites/pterclub.com/config.json
同样也是正在下载无法判断是否acive ,统一标志为inactive
> pter 做种信息支持

- resource/sites/pthome.net/config.json
> pthome 做种信息获取

- resource/sites/hdstreet.club/config.json
- resource/sites/moecat.best/config.json
- resource/sites/yingk.com/config.json
> 蚂蚁类PT 做种信息获取及禁转标签支持(信息获取未完成)

- resource/sites/beyond-hd.me/config.json
- resource/sites/beyond-hd.me/getSearchResult.js
https://github.com/ronggang/PT-Plugin-Plus/issues/396
> Fix BHD获取种子详情页下载连接

- resource/sites/pt.btschool.club/config.json
> 学校 搜索中未下载识别为下载中得问题

- resource/sites/karagarga.in/browse.js
- resource/sites/karagarga.in/config.json
- resource/sites/karagarga.in/details.js
- feat: 增加KaraGarga browse和details页插件工具支持
> 增加KG browse和details页插件工具支持

- resource/schemas/AvistaZ/config.json
- resource/schemas/AvistaZ/getSearchResult.js
由于AvistaZ 的做种信息是直接在tr中，所以就写到脚本里了，config.json 里写的暂时不起作用。
由于没有博士站，可能需要再测试下博士站有没有问题。
另，由于exo的class name特殊，所以不能用全等
> AvistaZ搜索中做种信息获取

- resource/sites/uhdbits.org/getSearchResult.js
由于UHD user无看评论的权限，默认不显示栏位，但是评论数据还会正常显示。
会造成列数判断异常，从而导致数据错位
> Fix UHDbits 因是否显示评论造成的数据错位

- resource/schemas/UNIT3D/getSearchResult.js
- resource/sites/asiancinema.me/config.json
- resource/sites/dxdhd.com/config.json
本来想支持整个UNIT3D 的，但是看起来schemas 的config.json改了读不到
> AsianCinema 以及 DXDHD 的 搜索结果做种信息获取

- resource/sites/chdbits.co/config.json
> 增加 chd 搜索 下载进度 支持

- resource/sites/hdzone.me/config.json
增加了HDZone站点：
https://hdzone.me
已测试全部功能
未完全支持：
1、进度条暂无法支持状态，进度可以正常显示。
> 增加站点支持：HDZone

- resource/sites/www.torrentseeds.org/config.json
- resource/sites/www.torrentseeds.org/getSearchResult.js
增加了TorrentSeeds站点：
https://www.torrentseeds.org/
不支持：
1、IMDB搜索
2、进度条
> 增加站点支持：TorrentSeeds

- resource/sites/totheglory.im/config.json
> Fix ttg消息获取，评论被引用的提醒也进行提示

- resource/sites/pornbits.net/config.json
- resource/sites/pornbits.net/getSearchResult.js
增加了Pornbits站点：
https://pornbits.net/
> 增加站点支持：Pornbits

- resource/sites/leaguehd.com/config.json
- 基础框架NexusPHP
- 支持显示做种状态（同MT）
> feat: 添加站点LeagueHD

- resource/sites/orpheus.network/config.json
* 将OPS的框架调整到GazelleJSONAPI，搜索/个人数据更完善
* 进一步完善个人数据的采集
> fix: OPS调整框架，完善数据采集

- resource/sites/aidoru-online.me/config.json
~~做种体积还没完成~~
~~搜索还没调试~~
~~工具栏相关功能还没完善~~
~~搜索做种相关信息没有完善~~
但是图标目前搞不定
> 增加 aidoru-online.me

- resource/sites/filelist.ro/getSearchResult.js
> 修复FL搜索结果丢失第一行的问题

- resource/sites/orpheus.network/config.json
OPS最近主动屏蔽了一个原有的API，导致获取个人信息时出现错误
现通过网页解析方式获取受影响的信息
> fix: 解决OPS屏蔽了用户信息查询API的问题

- resource/sites/www.torrentseeds.org/config.json
- resource/sites/www.torrentseeds.org/details.js
- resource/sites/www.torrentseeds.org/torrents.js
> 增加TorrentSeeds站点工具栏支持

- resource/schemas/UNIT3D/config.json
- resource/schemas/UNIT3D/getSearchResult.js
- resource/sites/asiancinema.me/config.json
- resource/sites/beyond-hd.me/config.json
- resource/sites/dxdhd.com/config.json
https://github.com/ronggang/PT-Plugin-Plus/issues/487
Blutopia没法测试效果
另BHD修复了各种优惠标签的显示
> UNIT3D 模板更新

- resource/sites/1ptba.com/config.json
> docs: 新增站点1PTBAR

- resource/sites/blutopia.xyz/config.json
- resource/sites/cinemageddon.net/config.json
- resource/sites/cinemageddon.net/details.js
- resource/sites/hdbits.org/config.json
- resource/sites/karagarga.in/details.js
- HDBits:
- 增加HDBits PM消息数支持
- Karagarga:
- 增加种子详情页插件获取种子大小功能
- 修复种子详情页一键下载按钮不可用的问题
- 修复一键下载可能选错种子的问题
- CinemaGeddon:
- 增加种子详情页插件获取种子大小功能
- 修复一键下载可能选错种子的问题
- Blutopia:
- 修复UNI3D模板获取消息未对该站生效的问题
> 一些针对HDB, KG, CG和BLU的修复

- resource/sites/anthelion.me/config.json
- resource/sites/anthelion.me/getSearchResult.js
> feat:添加站点Anthelion

- resource/sites/www.empornium.me/config.json
EMP感觉满规范，挺好写的
~~目前差工具栏，不过感觉没啥大问题~~
测试了一段时间，感觉没啥问题
> feat: 增加站点 EMP(done)

- resource/sites/www.myanonamouse.net/config.json
- resource/sites/www.myanonamouse.net/details.js
- resource/sites/www.myanonamouse.net/getSearchResult.js
- resource/sites/www.myanonamouse.net/getUserSeedingTorrents.js
- src/background/user.ts
> feat(MAM): 新增站点MyAnonaMouse

- resource/sites/aidoru-online.me/config.json
- resource/sites/asiancinema.me/config.json
- resource/sites/oppaiti.me/config.json
AO图标我也不知道咋就好了
欧派支持下Nips(bonus)
> Fix AO图标&欧派 支持Nips(bonus),搜索默认只开All

- resource/sites/pt.sjtu.edu.cn/config.json
主要4种状态snatched_no_no(未完成未做种)、snatched_yes_yes(已完成在做种)
但是没法判断当前是否在下载
> Putao 搜索页面做种信息获取

- resource/sites/www.myanonamouse.net/config.json
- resource/sites/www.myanonamouse.net/torrents.js
1. confirmSize这个方法应该传入jQuery的selector而非text，之前理解错了XD
2. 覆写getSize方法以修改种子大小的正则表达式
> fix(MAM): confirmSize导致的无法推送种子的问题

- resource/sites/asiancinema.me/config.json
原有selector都是根据英文标签写的，但是现在ACM站点的语言选择策略似乎改变，找不到主动选择语言的位置，故添加中文标签的selector
> fix: 修正ACM个人信息获取

- resource/sites/hdfans.org/config.json
> 添加对hdfans.org站点的支持

- resource/sites/bt.neu6.edu.cn/config.json
feat: 增加`六维空间`支持
效果：
备注：六维空间不提供做种信息，做种部分留空；搜索问题由于Discuz的限制，`searchid`暂时没有什么好的生成方案；目前已支持获取用户统计信息
#132 算是支持了六维空间啦~
> feat: 增加`六维空间`支持

- resource/sites/hdhome.org/config.json
`hacktoberfest-accepted` label wanted!!!
> feat(HDHome): 补全各项功能

- resource/sites/hdcity.city/config.json
- resource/sites/pt.m-team.cc/config.json
`hacktoberfest-accepted` label wanted!!!
Fixes #607
> fix(M-Team,HDCity): 多语种下无法获取数据

- resource/sites/et8.org/config.json
- resource/sites/hddolby.com/config.json
- resource/sites/hdhome.org/config.json
- resource/sites/www.beitai.pt/config.json
#506 的第二项似乎站点已经修改了url，现在可以正常显示侧边栏，故本pr只解决了第一项
> feat: 补全功能

- resource/sites/www.cinematik.net/config.json
- fix: 更改`Cinematik`用户数据获取路径，以修复在一段时间不访问网站后无法读取用户数据而显示`未登录`的bug
> 修复TIK偶尔无法获取用户数据的问题

- resource/sites/www.pttime.org/config.json
> feat(pttime): add pttime site

- resource/i18n/zh-CN.json
> style: 修复文本错误

- resource/sites/aither.cc/config.json
add site support for aither.cc
> feat: add site support for aither.cc

- resource/i18n/en.json
- resource/i18n/zh-CN.json
- src/options/views/statisticCharts/SiteBase.vue
简单的给 https://github.com/ronggang/PT-Plugin-Plus/discussions/731 写了一个, 还未完成
> feat: 数据图表增加柱形图

- resource/sites/animebytes.tv/config.json
> feat: 新增AB站点

- src/options/views/statisticCharts/SiteBase.vue
> feat: 增强柱形图tooltip显示

- resource/sites/baconbits.org/config.json
> feat: 添加bB站点

- resource/sites/baconbits.org/config.json
> fix: bB做种体积显示为N/A

- resource/sites/hd.ai/config.json
- resource/sites/hd.ai/getSearchResult.js
> Support hd.ai site searching function

- resource/sites/pt.hdpost.top/config.json
> fix: HDPOST采用新UNIT3D架构

- resource/sites/ultrahd.net/config.json
> feat: 新增UltraHD

- resource/sites/www.haidan.video/config.json
- resource/sites/www.haidan.video/getSearchResult.js
- src/options/views/search/SearchTorrent.vue
> feat: 增加HaiDan

- resource/sites/animebytes.tv/config.json
> fix: AB上传下载量统计错误

- resource/sites/thegeeks.click/config.json
> feat: add TG site

- resource/i18n/en.json
- resource/i18n/zh-CN.json
- src/interface/common.ts
- src/options/views/Home.vue
- src/options/views/settings/Sites/Editor.vue
> feat: 增加消息提醒开关

- resource/sites/shadowthein.net/browse.js
- resource/sites/shadowthein.net/config.json
- resource/sites/shadowthein.net/details.js
- resource/sites/shadowthein.net/getSearchResult.js
根据 https://github.com/ronggang/PT-Plugin-Plus/pull/738#issuecomment-886512395 回复，我帮 @luckiestone  cherry-pick了iTS相关代码，变成了一个新的分支。
代码逻辑未改动，新增部分未测试。
> feat. adding partial iTS support for luckiestone

- resource/sites/broadcasthe.net/config.json
- resource/sites/broadcasthe.net/getSearchResult.js
- resource/sites/nebulance.io/config.json
- fix: 修补 bug
- 修复BroadcasTheNet搜索结果中出现周数后解析错误，顺便改了时区；
- 修复Nebulance积分百万位之后的解析错误。
> 修复BTN发布时间及NBL积分问题

- public/manifest.json
- resource/sites/www.haidan.video/config.json
- update/index.xml
> fix: wrong haidan favicon url

- resource/schemas/UNIT3D/config.json
- fix: 修复Blutopia积分显示错误的问题，模板中没有去除`,`应该是模板的共性问题，故在模板修改
> 修复BLU积分显示错误的问题

- resource/sites/animebytes.tv/config.json
> feat: AB add message count

- README.md
> Readme里增加最新版本获取引导 Update README.md

- resource/sites/animebytes.tv/config.json
- resource/sites/animebytes.tv/getSearchResult.js
- resource/sites/animebytes.tv/userTorrents.js
1. Fix batch download #923
Proof:
2. Fix broken search function.
Proof:
> fix: AB batch download and search function

- resource/sites/audiences.me/config.json
> feat: 适配Audiences站点

- resource/clients/synologyDownloadStation/init.js
> fix: 尝试支持DSM7

- resource/sites/aither.cc/getSearchResult.js
- resource/sites/jptvts.us/config.json
User info:
Search results:
----
Also, removed a redundant alert from my previous commit for aither.cc.
> feat: add support for jptvts.us

- resource/i18n/en.json
- resource/i18n/zh-CN.json
- src/options/i18n.ts
- src/options/main.ts
> fix: timeline's timeAgo and my join time's i18n support.

- resource/sites/www.skyey2.com/config.json
Proof of concept:
Since I don't have much data on the site, I tested the queries on browser:
> fix #978: SkyeySnow user info fetching.

- resource/sites/www.skyey2.com/config.json
The previous PR #985 used the wrong RegEx style.
This PR fixed my stupid mistake and here's a proof:
> Fix #978: updated SkyeySnow‘s broken regex to JS style - the real fix.

- resource/sites/bitbr/config.json
> 适配 bitbr.cc 获取个人数据

- resource/sites/bitbr/config.json
- resource/sites/sportscult.org/config.json
- resource/sites/sportscult.org/details.js
1. 修改 bitbr 站点tags描述
2. 适配sportscult站点，获取部分个人数据，可以分类搜索、拖放下载等
> 适配sportscult

- resource/i18n/en.json
- resource/i18n/zh-CN.json
- src/options/views/UserDataTimeline.vue
> feat: 时间线加入UID显示

- resource/sites/sportscult.org/config.json
修复 sportscult站点 joinTime数据不准确，导致时间线显示异常的问题
>  fix: 修补 bug

- resource/sites/totheglory.im/bookmarks.js
- resource/sites/totheglory.im/config.json
> 适配 听听歌收藏页面

- resource/schemas/NexusPHP/config.json
> 增加Opencd 感谢发布者按钮

- resource/sites/pt.soulvoice.club/config.json
> 聆音 适配阅听专区搜索

- resource/sites/cnlang.org/config.json
- resource/sites/cnlang.org/getUserSeedingTorrents.js
> feat: 适配 国语视界 获取个人数据

- resource/sites/www.skyey2.com/config.json
> fix:修复 天雪 获取做种体积错误

- resource/sites/www.skyey2.com/config.json
Reverts ronggang/PT-Plugin-Plus#1024
> Revert "fix:修复 天雪 获取做种体积错误"

- resource/sites/club.hares.top/config.json
> Fix: 修复白兔未读消息提示

- resource/sites/hdsky.me/config.json
> Fix:hdsky在种子详情页用PT助手复制链接到客户端无法下载种子

- resource/sites/resource.xidian.edu.cn/config.json
> feat: create rs pt

- resource/i18n/en.json
- resource/i18n/zh-CN.json
- src/options/views/Home.vue
> fix: 打开时显示最后的站点状态

- resource/sites/greatposterwall.com/config.json
> fix: GPW做种体积和魔力值

- resource/schemas/NexusPHP/config.json
- resource/sites/hudbt.hust.edu.cn/config.json
由于蝴蝶的做种页面class和其他NexusPHP不同，所以修改NexusPHP的filters
> fix 蝴蝶 做种数和做种体积

- src/options/components/SearchBox.vue
> 适配kiwi浏览器输入法可以直接搜索

- resource/sites/greatposterwall.com/getSearchResult.js
> fix: GPW 搜索结果(#1086)

- resource/sites/hdtime.org/config.json
> fix: HDTime 做种体积显示为 0

- resource/sites/hdbits.org/getSearchResult.js
- fix: 修复One Icon造成的搜索问题，经测试，未开启One Icon时原修复方式会误判，且某些搜索条件不一定有codec1，因此更改判断条件。
> 修复HDB "One Icon" 造成的搜索问题

- resource/sites/greatposterwall.com/config.json
> fix: update GPW

- resource/schemas/NexusPHP/config.json
- resource/sites/1ptba.com/config.json
- resource/sites/hdtime.org/config.json
- resource/sites/www.pttime.org/config.json
维护了 pttime hdchina 1ptbar hdtime 的部分显示问题
#1082 #1099
> fix: pttime 1ptbar hdtime 的做种数目及体积显示 hdchina 魔力显示

- resource/sites/gainbound.net/config.json
> feat:addsite:gainbound丐帮

- resource/sites/filelist.io/config.json
- fix: 修复FileList由于首页有其他用户时选择器出错，导致用户信息读取错误的bug
> 修复FileList用户信息读取错误的bug

- resource/sites/1ptba.com/config.json
- resource/sites/hdfans.org/config.json
- resource/sites/hdtime.org/config.json
> [fix] 1ptbar hdfans hdtime 做种体积不显示

- resource/sites/monikadesign.uk/config.json
> feat: 添加站点Monika

- resource/sites/asiancinema.me/config.json
按照项目UNIT3D默认的100条记录修改了ACM的搜索queryString
> Fix:ACM搜索最多返回25条记录

- resource/schemas/UNIT3D/getSearchResult.js
- resource/sites/hawke.uno/config.json
1. 添加对HUNO的支持
2. 修复部分新版UNIT3D站点在搜索结果中不能正确获取种子大小的问题
> feat:添加对HUNO的支持；修复部分新版UNIT3D站点在搜索结果中不能正确获取种子大小的问题

- resource/i18n/en.json
- resource/i18n/zh-CN.json
- resource/schemas/NexusPHP/config.json
- resource/schemas/UNIT3D/config.json
- resource/sites/lemonhd.org/config.json
- resource/sites/pt.keepfrds.com/config.json
- resource/sites/totheglory.im/config.json
- resource/sites/u2.dmhy.org/config.json
- src/background/user.ts
- src/interface/common.ts
- src/options/views/Home.vue
> feat:在数据页面增加NexusPHP和UNIT3D网站的时魔信息

- resource/schemas/GazelleJSONAPI/config.json
> feat:为GazelleJSONAPI架构添加时魔数据

- resource/sites/world-in-hd.net/getSearchResult.js
> 调整WiHD搜索结果Free标签颜色

- resource/i18n/en.json
- resource/i18n/zh-CN.json
- resource/schemas/UNIT3D/config.json
- resource/sites/asiancinema.me/config.json
- resource/sites/audiences.me/config.json
- resource/sites/blutopia.xyz/config.json
- resource/sites/chdbits.co/config.json
- resource/sites/greatposterwall.com/config.json
- resource/sites/hdsky.me/config.json
- resource/sites/jptv.club/config.json
- resource/sites/lemonhd.org/config.json
- resource/sites/monikadesign.uk/config.json
- resource/sites/pt.btschool.club/config.json
- resource/sites/pt.keepfrds.com/config.json
- resource/sites/pterclub.com/config.json
- resource/sites/totheglory.im/config.json
- resource/sites/u2.dmhy.org/config.json
- resource/sites/www.beitai.pt/config.json
- src/background/config.ts
- src/interface/common.ts
- src/options/views/Home.vue
```
export interface LevelRequirement {
level?: number;
name?: string;
// 间隔要求
interval?: number;
// 日期要求
requiredDate?: string;
// 上传数要求
upload?: number;
// 上传量要求
uploaded?: string | number;
// 下载量要求
downloaded?: string | number;
// 积分要求
bonus?: number;
// 做种积分要求
seedingPoints?:number;
// 保种体积要求
seedingSize?: number;
// 分享率要求
ratio?: number;
// 权限
privilege?: string;
}
```
> feat:参照扩展版的思路添加升级要求的功能

- resource/i18n/en.json
- resource/i18n/zh-CN.json
- resource/schemas/UNIT3D/config.json
- resource/sites/greatposterwall.com/config.json
- src/options/views/Home.vue
- src/options/views/UserDataTimeline.vue
还改了时间线图默认不显示网站名和模糊图标。commit的忘写了
> feat:抓取UNIT3D发布数；给升级规则添加独立的翻译；在用户名下方显示ID

- resource/i18n/en.json
- resource/i18n/zh-CN.json
- src/options/views/Home.vue
> feat:添加过滤列和是否显示做种积分

- src/options/views/Home.vue
> fix:修复加入时间列不显示的错误，并将id改成title

- resource/sites/hdatmos.club/config.json
- src/options/views/Home.vue
1. 修复了hda做种体积，加入升级要求
2. 过滤列不在直接保存到local，而是与其它开关一起通过调用store来保存
> Feature improve home UI

- src/options/views/search/KeepUpload.vue
> feat:辅助验证失败的种子，现在可以点击失败按钮直接删除

- resource/sites/filelist.io/config.json
- resource/sites/gainbound.net/config.json
- resource/sites/hdcity.city/config.json
- resource/sites/hddolby.com/config.json
- resource/sites/hdmayi.com/config.json
- resource/sites/hdpt.xyz/config.json
- resource/sites/hdvideo.one/config.json
- resource/sites/hhanclub.top/config.json
- resource/sites/pt.msg.vg/config.json
- resource/sites/ptchina.org/config.json
- resource/sites/ptsbao.club/config.json
- resource/sites/wintersakura.net/config.json
- resource/sites/www.hdarea.co/config.json
添加以下站点升级条件
+ filelist
+ gainbound
+ hdcity
+ hddolby
+ hdmayi
+ hdpt
+ hdvideo
+ hhanclub
+ ptmsg
+ ptchina
+ ptsbao
+ wintersakura
+ hdarea
> feat:添加部分站点升级条件

- resource/sites/greatposterwall.com/getSearchResult.js
> feat(GPW):在副标题最后添加releaseGroup

- resource/sites/hdatmos.club/config.json
> fix(hda):修复之前只统计前100个做种体积

- resource/sites/pterclub.com/config.json
> fix(pter):调整升级条件

- resource/schemas/NexusPHP/details.js
- resource/sites/hdsky.me/config.json
- resource/sites/lemonhd.org/config.json
- src/options/views/Home.vue
- src/service/filters.ts
> feat:在home使用新的icon，整数等级要求不再显示小数点；补充柠檬的等级要求

- resource/sites/kp.m-team.cc/config.json
> feat(m-team):增加时魔获取

- src/options/views/Home.vue
> fix:修复没有升级要求的站显示done图标

- resource/sites/kp.m-team.cc/config.json
-------
fix: https://github.com/pt-plugins/PT-Plugin-Plus/issues/1230
> fix(m-team): 修复馒头无法读取黄星用户时魔的问题

- resource/sites/springsunday.net/config.json
> feat(ssd): 增加读取时魔

- resource/schemas/NexusPHP/config.json
-------
发现 ssd 的英文页面读不出魔力值，修复了下，应该对其它 NexusPHP 站点的英文页面也有效。
> fix: 修复部分站点英文页面无法读取魔力值的问题

- resource/sites/lemonhd.org/config.json
> fix(lemonhd): 修复读取时魔未处理千位分隔符的问题

- resource/sites/et8.org/config.json
> feat(tccf): 增加等级详情

- resource/sites/u2.dmhy.org/config.json
> fix(u2): 精简时魔代码

- resource/sites/pthome.net/config.json
> feat(pthome): 增加升级条件

- .github/workflows/build_canary.yml
Oh, Last mr clean this commit....
> fix(ci): canary may tag on wrong branch

- resource/sites/1ptba.com/config.json
- resource/sites/carpt.net/config.json
- resource/sites/hdatmos.club/config.json
- resource/sites/hdfans.org/config.json
- resource/sites/hdmayi.com/config.json
- resource/sites/hdpt.xyz/config.json
- resource/sites/hhanclub.top/config.json
- resource/sites/ptchina.org/config.json
修复以下站点搜索结果中的种子状态和进度
+ 1ptba
+ carpt
+ hdatmos
+ hdfans
+ hdmayi
+ hdpt
+ hhanclub
+ ptchina
> fix:修复部分站点搜索结果中的种子状态和进度

- resource/sites/byr.pt/config.json
> feat(byr.pt): 增加升级条件

- resource/sites/hudbt.hust.edu.cn/config.json
- resource/sites/nanyangpt.com/config.json
- resource/sites/pt.sjtu.edu.cn/config.json
- resource/sites/pt.soulvoice.club/config.json
feat(hudbt，sjtu，nanyang和soulvoice): 增加升级条件
> feat(hudbt，sjtu，nanyang和soulvoice): 增加升级条件

- resource/sites/ultrahd.net/config.json
> feat(ultrahd):增加升级条件、做种体积

- resource/sites/gay-torrents.org/config.json
- resource/sites/gay-torrents.org/getSearchResult.js
- resource/sites/www.gaytor.rent/getSearchResult.js
> fix(GTorg):时区与下载

- resource/sites/et8.org/config.json
- resource/sites/open.cd/config.json
- add levelRequirements for OpenCD
- fix categories for TCCF
> Update configurations of OpenCD & TCCF

- resource/sites/club.hares.top/config.json
> feat(hares): 增加升级条件

- resource/schemas/TNode/common.js
- resource/schemas/TNode/config.json
- resource/schemas/TNode/details.js
- resource/schemas/TNode/getSearchResult.js
- resource/schemas/TNode/torrents.js
- resource/sites/zhuque.in/config.json
- src/background/pageParser.ts
- src/background/searcher.ts
- src/background/user.ts
- src/interface/common.ts
- src/interface/enum.ts
- src/service/favicon.ts
- src/service/public.ts
- feat: allow post json payload for search
- feat: allow replace $var$ in header.(site selector)
- feat: New site zhuque.in
- fix: second replaceKey in searcher.ts will overwrite first replaceKey
> <feat> New site zhuque.in

- resource/schemas/TNode/getSearchResult.js
forget add site in the search results. add it back.
> fix: add site in results of /schemesTNode/getSearchResult

- src/options/views/Home.vue
> fix: 升级要求悬浮框中的数据引用错误

- resource/sites/cyanbug.net/config.json
希望新增大青虫站点支持，与新增自定义站点相比，本次更新修复了保种数据和用户等级等信息的获取。
> feat: 新增大青虫站点支持

- resource/sites/ccfbits.org/config.json
Add level requirements for CCFBits
> feat(CCFBits): Level Requirements for CCFBits

- resource/sites/ccfbits.org/config.json
- resource/sites/www.torrentleech.org/config.json
Adding Privilege of each user class for TorrentLeech: levelRequirements
> feat(TorrentLeech): Level Requirements: Privilege

- resource/sites/springsunday.net/config.json
> fix(ssd): get seeding & seedingSize

- resource/sites/springsunday.net/config.json
> fix(ssd): remove the comma from the get number

- src/options/views/statisticCharts/SiteBase.vue
Add briefly dark mode support for SiteBase statistic Charts.
#928
> feat(statisticCharts): briefly supports dark mode

- resource/sites/pt.keepfrds.com/config.json
Update the levelRequirements of keepfrds.com to sync with the new description modified/published by the site.
> fix(keepfrds): update levelRequirements

- resource/sites/www.gaytor.rent/config.json
> feat:增加gaytor.rent的cdn

- resource/sites/ourbits.club/config.json
> fix(ourbits): level requirements

- resource/sites/www.morethantv.me/config.json
> fix(mtv): torrent detail page download fail.

- resource/sites/zmpt.cc/config.json
> feat(zmpt): add site zmpt

- resource/sites/1ptba.com/config.json
> fix: 更新1ptba升级条件

- resource/sites/hdzone.me/config.json
> fix: 添加升级条件

- resource/sites/discfan.net/config.json
- resource/sites/hdzone.me/config.json
> feat(discfan): 添加升级条件

- resource/sites/hdhome.org/config.json
> feat(hdhome): 更新升级条件

- resource/sites/hdhome.org/config.json
> fix(hdh): 升级条件写错

- resource/sites/pt.2xfree.org/config.json
> feat(2xFree): new site

- resource/sites/pt.hd4fans.org/config.json
> feat(hd4fans): 添加升级条件

- resource/sites/kamept.com/config.json
- resource/sites/pt.2xfree.org/config.json
* 修复了 kamept, 2xfree 做种体积的获取
[dist.zip](https://github.com/pt-plugins/PT-Plugin-Plus/files/11258547/dist.zip)
> fix(做种体积): kamept, 2xfree

- resource/sites/leaves.red/config.json
> feat:新增红叶适配

- resource/sites/piggo.me/config.json
> feat:新增猪猪适配儿童区

- resource/sites/www.gamegamept.com/config.json
> feat: add gamegamept.com

- resource/sites/leaves.red/config.json
> feat:新增加红叶有声区合适配

- resource/sites/carpt.net/config.json
https://carpt.net/forums.php?action=viewtopic&forumid=1&topicid=236
> fix(carpt): 更新CarPT升级条件

- resource/schemas/NexusPHP/getSearchResult.js
> fix(byr):修复byr种子获取数据丢失

- resource/sites/xingtan.one/config.json
> 杏林更新为杏坛，更新域名，添加升级条件

- resource/sites/monikadesign.uk/config.json
> fix:修复MDU时魔显示错误的问题

- resource/sites/pt.soulvoice.club/config.json
> fix:修改聆音阅听区页面地址，修复获取聆音做种数、做种体积错误问题

- resource/sites/www.morethantv.me/config.json
> fix(MTV): 修复种子详情页工具栏下载

- resource/sites/dajiao.cyou/config.json
> site: add 打胶

- resource/sites/dajiao.cyou/config.json
> fix:Supplement missing fields of dajiao

- resource/sites/beyond-hd.me/config.json
> fix: BHD种子详情下载和感谢按钮

- resource/sites/zmpt.cc/config.json
> feat(zmpt): update level requirements

- resource/sites/www.gamegamept.com/config.json
- resource/sites/www.okpt.net/config.json
> feat : add OKPT

- resource/sites/pt.soulvoice.club/config.json
> feat: 更新升级条件

- resource/sites/pt.soulvoice.club/config.json
- resource/sites/www.gamegamept.com/config.json
- resource/sites/www.gamegamept.com/torrents.js
- resource/sites/www.okpt.net/config.json
- resource/sites/www.okpt.net/torrents.js
> feat: OKPT GGPT

- resource/sites/pt.2xfree.org/config.json
> site: update 2xfree PU requirement

- resource/sites/tjupt.org/config.json
> fix(tujpt): get bonusPerHour

- resource/sites/passthepopcorn.me/config.json
> Level Requirements and BonusPerHour for PTP

- resource/sites/fsm.name/config.json
> fix(FSM): 修复FSM站点个人信息

- resource/sites/pt.2xfree.org/config.json
> site(2xfree): 特别区适配

- resource/sites/bwtorrents.tv/config.json
> fix: BWT 做种数,魔力

- resource/sites/telly.wtf/config.json
> feat: add telly.wtf

- resource/sites/pandapt.net/config.json
- resource/sites/pt.hdupt.com/config.json
feat: add pandapt.net and add Level Requirements of HDU
> feat: add pandapt.net and add Level Requirements of HDU

- resource/sites/leaves.red/config.json
> fix: 修复红叶时魔获取

- resource/sites/desitorrents.tv/config.json
> feat: add Desitorrents

- resource/schemas/UNIT3D/config.json
- resource/sites/desitorrents.tv/config.json
> fix: Desitorrents user info

- resource/schemas/UNIT3D/getSearchResult.js
- resource/sites/www.torrentseeds.org/config.json
> fix: TorrentSeeds search

- resource/sites/audiences.me/config.json
悲惨世界(Peasant)	 	当以下情况时将被自动降至本级：
1.如果你已经下载了超过80GB，你的分享率却低于0.8。
2.如果你已经下载了超过200GB，你的分享率却低于0.85。
3.如果你已经下载了超过400GB，你的分享率却低于0.9。
4.如果你已经下载了超过800GB，你的分享率却低于0.95。
5.如果你已经下载了超过1024GB，你的分享率却低于1。
请记住，此等级意味着您的账号处于受限状态（参考用户等级详情），您需要尽快提升分享率！
年轻气盛(Power User)	 	必须注册至少5周，并且下载至少120G，分享率大于2.0，做种积分达到100,000。
当条件符合时将被自动提升。注意，无论何时，如果你的分享率低于1.9，你将自动降级。
江湖儿女(Elite User)	 	必须注册至少15周，并且下载至少240G，分享率大于2.5，做种积分达到200,000。
当条件符合时将被自动提升。注意，无论何时，如果你的分享率低于2.4，你将自动降级。
街头霸王(Crazy User)	 	必须注册至少24周，并且下载至少400G，分享率大于3.0，做种积分达到400,000。
当条件符合时将被自动提升。注意，无论何时，如果你的分享率低于2.9，你将自动降级。
步履不停(Insane User)	 	必须注册至少40周，并且下载至少600G，分享率大于3.5，做种积分达到640,000。
当条件符合时将被自动提升。注意，无论何时，如果你的分享率低于3.4，你将自动降级。
杰出公民(Veteran User)	 	必须注册至少60周，并且下载至少1024G，分享率大于4.0，做种积分达880,000。
当条件符合时将被自动提升。注意，无论何时，如果你的分享率低于3.9，你将自动降级。
头号玩家(Extreme User) …
> fix(audiences):调整升级条件

- resource/sites/pterclub.com/config.json
https://wiki.pterclub.com/wiki/%E7%94%A8%E6%88%B7%E5%88%86%E4%BA%AB%E7%8E%87%E5%8F%8A%E7%AD%89%E7%BA%A7%E8%AF%B4%E6%98%8E
> fix(pter): 更新等级权限

- resource/schemas/UNIT3D/config.json
- resource/schemas/UNIT3D/getSearchResult.js
* fix: Blu torrent seeding status
* fix: Blu torrent seeding status
> fix: Blu torrent seeding status

- resource/sites/pt.eastgame.org/config.json
> fix: TLF torrent seeding status

- resource/sites/www.icc2022.com/config.json
> feat: icc2022 新增保种积分要求

- resource/sites/shadowflow.org/config.json
> Level Requirements

- .github/ISSUE_TEMPLATE/bug-report-cn.md
> docs: update issue template

- resource/sites/pterclub.com/config.json
更正 Pter 升级条件，见[Pter 用户分享率及等级说明
](https://wiki.pterclub.com/wiki/%E7%94%A8%E6%88%B7%E5%88%86%E4%BA%AB%E7%8E%87%E5%8F%8A%E7%AD%89%E7%BA%A7%E8%AF%B4%E6%98%8E)
> fix(pter): 更正 Pter 升级条件

- resource/sites/hdfun.me/config.json
> fix(HDZone): update domain

- resource/sites/www.pttime.org/config.json
> fix:  Add PTT search for 9Kg

- resource/sites/kufei.org/config.json
> feat: add kufei.org

- resource/sites/discfan.net/config.json
> fix: DiscFan seedingSize

- resource/sites/pt.2xfree.org/config.json
fix: Level Requirements of 2xFree
> fix: Level Requirements of 2xFree

- resource/i18n/zh-CN.json
- src/options/views/Home.vue
- src/options/views/UserDataTimeline.vue
@fzlins @Rhilip  @pjw20911 
需要注意的 commit: cfe072b44f8385c53601ce800a8445f621b4db95
> 如果遇到下面类型的问题，可以先尝试重新刷新个人数据  
* ~~jpop~~ 强制转换后正常
* ~~azusa~~ 刷新后正常
> feat(#973): 发种数量统计

- resource/sites/kufei.org/config.json
- resource/sites/rousi.zip/config.json
feat: add rousi.zip and fix: Level Requirements of kufei
> feat: add rousi.zip and fix: Level Requirements of kufei

- resource/sites/wintersakura.net/config.json
Fix-wintersakura: Use total bonusPerHour instead of basic bonus
> Fix-wintersakura: Use total bonusPerHour instead of basic bonus

- resource/sites/desitorrents.tv/config.json
> fix(Desitorrents): message count

- resource/sites/hhanclub.top/config.json
> fix(hhanclub): 数据量 #1533

- resource/sites/hhanclub.top/config.json
- resource/sites/hhanclub.top/getSearchResult.js
> feat(hhanclub):适配憨憨新UI搜索功能

- resource/sites/hhanclub.top/config.json
- resource/sites/hhanclub.top/getSearchResult.js
> fix(hhanclub):修复做种体积和搜索

- resource/sites/hhanclub.top/config.json
解决 https://github.com/pt-plugins/PT-Plugin-Plus/issues/1529#issuecomment-1692979006
> fix(hhanclub):修复做种积分

- resource/schemas/NexusPHP/getSearchResult.js
> fix(#1395): piggo 发布时间

- resource/sites/ianon.app/config.json
> feat: add support for ianon.app

- resource/sites/www.ptlsp.com/config.json
feat: add support for www.ptlsp.com, correct the value obtained.
> feat: add www.ptlsp.com

- resource/sites/pt.dhtclub.com/config.json
- resource/sites/pt.itzmx.com/config.json
- resource/sites/ptcafe.club/config.json
- resource/sites/share.ilolicon.com/config.json
- resource/sites/wukongwendao.top/config.json
- resource/sites/www.oshen.win/config.json
fix: 适配站点：咖啡、奥申、爱萝莉、DHT、PT 分享、悟空问道
> fix: 适配站点：咖啡、奥申、爱萝莉、DHT、PT 分享、悟空问道

- public/index.html
> fix(#1157): 不要翻译此网页

- resource/sites/rousi.zip/config.json
fix: Level Requirements of rousi
> fix: Level Requirements of rousi

- resource/sites/lst.gg/config.json
支持 lst.gg 站点
已测试获取站点数据、种子搜索及下载功能均正常
> feat: add lst.gg

- resource/sites/www.pttime.org/config.json
> fix(PTT): 搜索结果添加种子状态及进度

- resource/i18n/en.json
- resource/i18n/zh-CN.json
- src/options/views/statisticCharts/SiteBase.vue
> Feat: Add hourly bonus chart to monitoring daily difference

- resource/sites/hdarea.club/config.json
fix: Level Requirements of HDArea
> fix: Level Requirements of HDArea

- resource/sites/www.gamegamept.com/config.json
修复了因config.json中单位不正确造成的等级显示错误
> fix(ggpt): 升级条件写错

- resource/sites/hhanclub.top/config.json
> fix: levelName of HHanClub

- resource/schemas/TNode/config.json
> Feature: add uploads count for TNode

- resource/clients/qbittorrent/init.js
* 应该在 this.getSessionId 后判断 403
#1573
> fix: qb 下载 403

- src/background/user.ts
> fix: 因为缺少了站点信息导致日志不完整

- src/options/views/statisticCharts/SiteBase.vue
* 强转数值类型 #1509 @Meng-Lan 
* 格式化数据
* 站点数量大于24左右, Tooltip 会显示不完全. 暂时不考虑修复, 欢迎 PR
> fix: 时魔图表异常

- resource/sites/rousi.zip/config.json
修复rousi.zip的status和progress bar
> fix(rousi): status and progress

- resource/sites/ubits.club/config.json
> fix(UBits): 解决了UBits的搜索结果不显示种子进度的问题

- resource/sites/kufei.org/config.json
fix: Level Requirements of KuFei
> fix: Level Requirements of KuFei

- resource/sites/hdfans.org/config.json
> fix(HDFans): status and progress

- resource/sites/pt.0ff.cc/config.json
> fix(freefarm): name, desc, progression and status

- resource/schemas/UNIT3D/config.json
> fix(Blu): completed status

- resource/sites/hudbt.hust.edu.cn/config.json
fix: seeding and seedingSize of HUDBT
> fix: seeding and seedingSize of HUDBT

- resource/sites/hudbt.hust.edu.cn/config.json
> fix: uploads of HUDBT

- resource/sites/club.hares.top/config.json
- resource/sites/hdchina.org/config.json
- resource/sites/kp.m-team.cc/config.json
- fix: fix:uploads (HDChina,M-Team,Hares)
> fix uploads: (HDChina,M-Team,Hares)

- resource/sites/desitorrents.tv/config.json
> fix(desitorrents): login status

- resource/sites/dicmusic.com/config.json
- fix: the domain of dicmusic
update the correct domain
> fix: the domain of dicmusic

- resource/sites/hhanclub.top/config.json
> fix(hhan): message count

- resource/sites/www.agsvpt.com/config.json
适配站点 agsv ,agsv  全称为 Arctic global seed vault，是一个综合性站点
> feat(agsv):适配站点 agsv

- resource/sites/broadcasthe.net/config.json
> feat(BTN): bonus per hour

- resource/sites/anthelion.me/config.json
> feat(ant): better anthelion support

- resource/sites/sharkpt.net/config.json
> feat: restore sharkpt.net

- resource/sites/hdatmos.club/config.json
解决了阿童木站的两个问题
1、Insane等级的分享率要求
2、搜索进度及状态
> fix(hda): 等级要求、进度、状态

- resource/sites/anthelion.me/config.json
- resource/sites/anthelion.me/getSearchResult.js
- resource/sites/blutopia.cc/config.json
> fix blu, ant

- resource/sites/star-space.net/config.json
> chore: shadowflow.org -> star-space.net

- resource/sites/desitorrents.tv/config.json
> fix(dt): my data

- resource/sites/star-space.net/config.json
> fix(star-space): missing `formerHosts`

- resource/sites/anthelion.me/config.json
- resource/sites/hhanclub.top/config.json
> fix(ant), fix(hh)

- resource/sites/sharkpt.net/config.json
fix: Level Requirements of SharkPT
> fix: Level Requirements of SharkPT

- resource/sites/www.agsvpt.com/config.json
> fix(agsv):更新账号升级条件

- resource/sites/zmpt.cc/config.json
> fix(zmpt): 织梦魔力值修改为 "电力值"，修复上传进度；

- resource/sites/anthelion.me/config.json
> fix(ant): message count

- resource/sites/kimoji.club/config.json
> feat(kimoji):适配站点 kimoji

- resource/schemas/NexusPHP/config.json
> feat: 支持 NP 架构站点的 HnR 统计

- resource/sites/hhanclub.top/config.json
- resource/sites/hhanclub.top/getSearchResult.js
> fix(hhanclub): add torrent tag, seeding progress and status

- resource/sites/ptchdbits.co/config.json
> fix(chd): progress

- resource/sites/www.morethantv.me/config.json
> fix(mtv): remove duplicate download link

- resource/sites/animebytes.tv/config.json
> fix(ab): strip the timezone from join time

- resource/sites/bwtorrents.tv/config.json
> fix(bwt): add skipIMDbId and skipNonLatinCharacters

- public/manifest.json
- resource/i18n/en.json
- resource/i18n/zh-CN.json
- src/background/service.ts
- src/interface/common.ts
- src/interface/enum.ts
- src/options/components/Permissions.vue
- src/options/views/settings/Base/Index.vue
* 基于 chrome.alarm 实现
* 通用设置里面开关, 默认旧版
> ref: 使用 chrome 定时权限触发定时刷新

- resource/sites/ptchdbits.co/config.json
> fix(chd): HnR count

- resource/sites/www.gaytor.rent/config.json
- resource/sites/www.gaytor.rent/getSearchResult.js
original
change web link to rss link
status bar
> fix(gtru): download failed

- resource/sites/www.agsvpt.com/config.json
> fix(agsv)修复做种体积展示

- resource/sites/kufirc.com/config.json
- resource/sites/kufirc.com/getSearchResult.js
> feat: add kufirc

- resource/sites/abtorrents.me/config.json
- resource/sites/abtorrents.me/getSearchResult.js
> feat: add ABTorrents

- resource/sites/www.gaytor.rent/config.json
> fix(gtru): support uploads

- resource/sites/www.agsvpt.com/config.json
> fix(agsv) 更新升级分享率要求

- resource/sites/ecustpt.eu.org/config.json
> fix: change ecustpt domain

- resource/sites/ecustpt.eu.org/config.json
> fix(ecust):incorrect seedingPoints

- resource/sites/qingwapt.com/config.json
- resource/sites/www.qingwapt.com/config.json
> fix(qingwa): bouns alias and level name

- resource/sites/our.kelu.one/config.json
> feat: add Kelu

- resource/sites/ecustpt.eu.org/config.json
fix(ecust):site update seedingPoints
> fix(ecust):site update seedingPoints

- resource/sites/www.agsvpt.com/config.json
> fix(AGSV) 更新账户升级信息

- resource/sites/xp.m-team.io/config.json
- src/background/searcher.ts
修复m-team的imdb搜索功能
fix https://github.com/pt-plugins/PT-Plugin-Plus/issues/1823 https://github.com/pt-plugins/PT-Plugin-Plus/issues/1811
> fix(mt): imdb search

- public/manifest.json
- resource/sites/audiences.me/config.json
- src/background/service.ts
> fix(audiences):修复做种数、做种体积、发种数获取

- resource/sites/www.pttime.org/config.json
- src/background/searcher.ts
- src/options/views/search/SearchTorrent.ts
禁用ptt的imdb搜索功能。这网站不仅搜不出结果还搜出一堆无关结果来造成污染。
修复imdb搜索时如果所有网站都不支持imdb搜索，一直显示loading状态的问题
> fix(ptt): disable imdb search

- resource/sites/fsm.name/config.json
- resource/sites/fsm.name/getSearchResult.js
尝试修复FSM搜索问题 显示效果如图
依旧存在显性BUG
- 发布时间不正确 当前显示为搜索发起时间
- 将tags作为副标题（站点无副标题，只为增加信息）显示时 tags为空时显示不美观
> fix(fsm): 搜索问题

- src/background/service.ts
- src/interface/enum.ts
> fix(audiences):支持Microsoft Edge浏览器获取做种体积

- resource/sites/x-ite.me/config.json
> feat (x-ite): 适配站点

- vite.config.background.ts
- vite.config.content.ts
- vite.config.ts
close https://github.com/pt-plugins/PT-Plugin-Plus/issues/1857
> build: disable rollup treeshake because we use eval

- resource/sites/hddolby.com/config.json
> fix(hdd): bonus per hour

- resource/sites/fsm.name/config.json
> fix(fsm): should show `N/A` for unknown value

- resource/sites/fsm.name/config.json
> fix(fsm): join time

- resource/sites/piggo.me/config.json
> fix(pig): HnR count.

- resource/sites/fsm.name/getSearchResult.js
> fix(fsm): search result link

- resource/sites/crabpt.vip/config.json
> fix(xhb): 更新升级条件

- resource/sites/www.yemapt.org/config.json
> feat(yemapt): 增加新的等级描述、做种数、做种体积、时魔、保种数

- resource/sites/pterclub.com/config.json
This reverts commit 68604b82fe3c1c2174fb04ca6cdfb232272ee1b3.
猫的升级条件是以审核过的非死种为要求。在未解决这个问题前先回退了。
> Revert "fix(pterclub): fix uploads count and rename the level name"

- resource/sites/desitorrents.tv/config.json
- resource/sites/torrent.desi/config.json
> fix(dt): domain change

- resource/sites/crabpt.vip/config.json
- resource/sites/hdfans.org/config.json
- resource/sites/ptcafe.club/config.json
- resource/sites/rousi.zip/config.json
- resource/sites/share.ilolicon.com/config.json
https://github.com/pt-plugins/PT-Plugin-Plus/issues/1888
因为好多站我都没有，如果没啥反馈的话我就合了
不过我不太清楚蟹黄堡的影视tag为啥被拿了@Atenolol9572
> feat: some site change

- resource/sites/pt.sjtu.edu.cn/config.json
修复 PuTao 的做种数获取。先前的版本获取到的做种数实际上是发布数。
本地已通过测试。
> fix(putao): seeding number

- resource/sites/star-space.net/config.json
- resource/sites/star-space.net/details.js
可正常获取数据、搜索等等
消息提醒和分享率没有适配，~~因为我没有分享率~~
> fix(Starspace):修复部分数据获取和搜索

- resource/sites/www.pttime.org/config.json
> fix(ptt): user level info. #1955

- resource/sites/www.pttime.org/config.json
- feat: 添加新功能 2024-07-29 ptt user level change
> feat: 2024-07-29 ptt user level change

- resource/sites/pt.btschool.club/config.json
- src/background/user.ts
> fix(btschool): 修复数据获取

- resource/sites/star-space.net/config.json
- src/interface/types.expand.js
> fix(star-space):修复搜索结果时间格式不正确

- resource/schemas/Luminance/config.json
- resource/sites/pornbay.org/config.json
适配 PornBay, 顺带修复了对应 Luminance 架构的一些错误，并添加了助手工具栏。
对 Luminance 架构的修改已在 Kufirc 和 HappyFappy 中测试通过。
> feat(pornbay): new site

- resource/sites/www.cathode-ray.tube/config.json
> feat(cathode-ray.tube): new site

- resource/sites/milkie.cc/config.json
- resource/sites/milkie.cc/getSearchResult.js
#1902 
注意：
1. 鉴权 Token 需要在 Local Storage 里拿，貌似一直有效
2. 密钥在 https://milkie.cc/settings/security 里复制 API key (仅对下载种子有效)
> feat(milkie): new site

- resource/sites/fsm.name/config.json
- resource/sites/milkie.cc/config.json
- resource/sites/xp.m-team.cc/config.json
- src/options/views/settings/Sites/Editor.vue
> feat: authTokenTip

- resource/sites/login.superbits.org/config.json
- resource/sites/login.superbits.org/getSearchResult.js
> feat(superbits): searchEntry

- resource/sites/digitalcore.club/config.json
- resource/sites/digitalcore.club/getSearchResult.js
> feat(digitalcore): searchEntry

- resource/sites/fsm.name/config.json
> fix(fsm): joinTime & add default apiCdn

- resource/sites/hhanclub.top/getSearchResult.js
> fix(hhanclub): 搜索结果无法获取发布时间

- resource/sites/www.ptzone.xyz/config.json
> 增加适配PTzone

- src/background/controller.ts
> fix: 右键发送到使用cdn匹配站点

- resource/sites/raingfh.top/config.json
> feat(raingfh): new site

- resource/schemas/NexusPHP/common.js
- resource/sites/club.hares.top/config.json
- resource/sites/club.hares.top/details.js
- resource/sites/club.hares.top/getSearchResult.js
- resource/sites/club.hares.top/torrents.js
- src/background/user.ts
> fix(hares):修复数据获取，种子搜索

- resource/sites/lemonhd.club/config.json
> feat: add lemonhd

- src/options/views/settings/SiteSearchEntry/Index.vue
> fix:  部分站点无法显示自定义搜索入口

- resource/sites/discfan.net/config.json
> feat(discfan): support search status

- resource/schemas/Luminance/config.json
修复 happyfappy joinTime 不正确的问题，在其他站也测试正常
> fix(luminance): adjust joinTime position

- resource/sites/ptlgs.org/config.json
> feat: add site support: PTLGS

- resource/sites/byr.pt/config.json
- resource/sites/www.hdkyl.in/config.json
fix(hdkyl): seeding size.
fix(byr): bonus per hour.
Local test passed.
> fix: some data query problem (byr and hdkyl)

- resource/sites/crabpt.vip/config.json
> fix(crabpt):更新蟹黄堡升级条件和用户权限

- resource/sites/sunny/config.json
- yarn.lock
> feat(sunny): new site

- resource/sites/www.hdkyl.in/config.json
Extreme User及以上用户会永远保留账号
https://t.me/c/1276598895/125233
> fix: HDkylin保号条件

- resource/sites/eiga.moi/config.json
- resource/sites/jptv.club/config.json
> fix(ACM, jptv) torrent search

- resource/sites/club.hares.top/config.json
> fix(Hares): 修复入站时间获取

- resource/sites/qingwapt.com/config.json
Update qingwapt.com newest promotion rule (2024/12/13 17:00)
Wiki is not modified for now, and will be updated later.
> fix(qingwapt): update qingwa new promotion rule

- resource/sites/qingwapt.com/config.json
`<fix>(qingwapt): 做种体积异常修复`
- fix: 修补 bug
修复bug #2082
> fix(qingwapt): 做种体积异常修复

- resource/i18n/en.json
- resource/i18n/zh-CN.json
- src/options/views/search/SearchTorrent.ts
- src/options/views/search/SearchTorrent.vue
- feat: 添加新功能
在搜索结果中，新增了排除包含指定词的结果 #2108 
效果如下
> feat:搜索结果中增加排除功能

- resource/sites/xp.m-team.cc/common.js
fix(m-team): Fix the log printing printing
fix: 修补 bug
> fix(m-team): Fix the log printing printing

- resource/sites/sunny/config.json
> fix: 更新sunny升级规则

- resource/sites/kufei.org/config.json
> fix: 更新库非等级

- resource/sites/cyanbug.net/config.json
> fix: 更新大青虫等级

- resource/sites/raingfh.top/config.json
> fix: 更新雨等级

- resource/sites/zmpt.cc/config.json
> fix: 更新织梦等级

- resource/sites/hdatmos.club/config.json
> fix: 更新HDATMOS等级

- resource/sites/pt.0ff.cc/config.json
> fix: 更新农场等级

- resource/sites/hdtime.org/config.json
> fix: 更新hdtime等级

- resource/sites/share.ilolicon.com/config.json
> fix: 更新ilolicon等级

- resource/sites/kamept.com/config.json
> fix: 更新kamept等级

- resource/sites/wukongwendao.top/config.json
> fix: 更新悟空等级

- resource/sites/pt.eastgame.org/config.json
> fix: 更新eastgame等级

- resource/sites/pt.hdupt.com/config.json
> fix: 更新hdu等级

- resource/sites/www.icc2022.com/config.json
> fix: 更新icc等级

- resource/sites/www.hitpt.com/config.json
> fix: 更新hit等级

- resource/sites/audiences.me/config.json
> fix: 更新观众等级

- resource/sites/www.oshen.win/config.json
> fix: 更新oshen等级

- resource/sites/52pt.site/config.json
> fix: 更新52pt名称

- resource/sites/www.haidan.video/config.json
> fix: 更新海胆等级

- resource/sites/cspt.top/config.json
> feat(财神):适配站点 财神

- resource/sites/tmpt.top/config.json
> feat(唐门):适配站点 唐门

- resource/sites/www.ptlover.cc/config.json
> feat:适配站点 afun

- resource/sites/1ptba.com/config.json
> fix: 更新1ptba等级信息

- resource/sites/hdfans.org/config.json
> fix: hdfans更新权限

- resource/sites/www.agsvpt.com/config.json
> fix(agsv):更新升级条件

- resource/sites/lst.gg/config.json
按照 https://lst.gg/stats/groups/requirements 文档更新用户升级条件，已验证
> fix(lst.gg): 更新升级条件

- resource/schemas/UNIT3D/config.json
- resource/sites/aither.cc/config.json
- resource/sites/animebytes.tv/config.json
- resource/sites/orpheus.network/config.json
> fix: fix u3d uploads and ops ath ab level

- resource/sites/sanpro.pw/config.json
> feat(伞):适配站点 伞

- resource/sites/fearnopeer.com/config.json
架构 UNIT3D, 已验证各功能运作正常
按照 https://fearnopeer.com/stats/groups/requirements/ 匹配了用户升级条件，已验证
> feat:: support FNP (fearnopeer.com)

- resource/sites/hspt.club/config.json
本次添加站点 [回声PT](https://hspt.club/)
添加内容：
- 等级规则
- 搜索规则
- 魔力数据
测试截图：
> feat: add site hspt

- resource/sites/sewerpt.com/config.json
> feat(site): 适配站点 下水道

- resource/sites/sunny/config.json
> fix(sunny): 修复等级规则错误

- resource/sites/azusa.wiki/config.json
> fix(azusa): getInfoAjaxCache

- resource/sites/1ptba.com/config.json
> 1pt等级更新做种积分要求

- resource/sites/xp.m-team.cc/common.js
fix(m-team): Callback failed when catching error
fix: 修补 bug
error时应该callback failed，而不是继续请求。
> fix(m-team): Callback failed when catching error

- resource/sites/bitporn.eu/config.json
refs: https://github.com/pt-plugins/PT-Plugin-Plus/issues/2213
> fix(site): try to fix bitporn user id miss take

- resource/sites/xp.m-team.cc/config.json
> feat(m-team):馒头增加未读消息提醒

- resource/sites/azusa.wiki/config.json
时魔表格的结构有所变化（不清楚是啥时候改的，也不清楚近期会不会再改，先提个draft）
> fix(azusa): update selector of bonusPerHour
