resource/schemas/NexusPHP/config.json
resource/sites/hdchina.org/config.json
resource/sites/open.cd/config.json
resource/sites/pt.meihezi.com/config.json
resource/sites/pter.club/config.json
resource/sites/tp.m-team.cc/config.json
src/options/views/settings/Sites/Add.vue

本patch包括两个commit（其实想再开一个pr的23333）
7d309af97f90ac01a607677451c2ddb257bfa540  style: 修改添加站点对话框
```
1. 不把站点全暴露给用户（因为站点过多，导致站点选择栏过长），而是推荐使用“搜索+下拉”的形式添加
2. 站点搜索支持host,name,url属性
```
56d70f66b511322e23aca57bf5c1c14f1ee3e514 style: 对NP构架站点静默搜索
```
在搜索字段中添加`&notnewword=1`使得搜索关键词不会出现在站点热门词中
```

style: 修改添加站点对话框 + 对NP构架站点静默搜索

---

resource/sites/whu.pt/config.json
test/src/BuildPlugin.ts

1. WHU的登出是用的一个post，所以在原NexusPHP模板下会出现未登录（因为找不到a[href*='logout.php']），因此将其改成了WHU页面的形式
2. 编译配置文件时不应依赖运行yarn build/dev编译出来的的dist文件夹，而应该是源文件夹，因为yarn res时还没有dist文件夹

 fix: 修复WHU个人信息页未登录Bug及首次运行yarn res时会找不到文件的问题

---

resource/sites/dicmusic.club/config.json
resource/sites/lztr.me/config.json
resource/sites/orpheus.network/config.json
resource/sites/redacted.ch/config.json

- feat: 添加lztr,red,ops,dic站点；
- 4个站点的搜索功能和下载，批量下载，批量复制均可使用；
- red,ops,dic的torrents.php页面尚且无法批量复制或下载；
- lztr适配最完全，概览也可正常使用。

add lztr,red,ops,dic site

---

resource/schemas/GazelleJSONAPI/config.json
resource/schemas/GazelleJSONAPI/getSearchResult.js
resource/schemas/GazelleJSONAPI/torrents.js
resource/sites/alpharatio.cc/config.json
resource/sites/broadcasthe.net/config.json
resource/sites/broadcasthe.net/getSearchResult.js
resource/sites/dicmusic.club/config.json
resource/sites/redacted.ch/config.json
resource/sites/uhdbits.org/config.json
resource/sites/uhdbits.org/getSearchResult.js

`feat:新增GazelleJSONAPI框架，并适配DIC和RED`
* 根据[JSON-API-Documentation](https://github.com/WhatCD/Gazelle/wiki/JSON-API-Documentation)新增GazelleJSONAPI框架。
* 目前适配了两个音乐站点DIC和RED，并且调整好了用户数据的采集。
`fix:修正了GazelleJSONAPI框架，并适配了DIC/RED/AR/UHD`
* 将用户数据做种体积加入到GazelleJSONAPI框架通用模块内
* 删除了部分无用的种子词条data属性，从而避免了一处显示bug
* 根据GazelleJSONAPI框架适配了DIC/RED/AR/UHD
* 增加了适配网站RED/AR/UHD的搜索分类
* UHD的种子页面采取原有的html解析方式，增加了副标题的显示
GazelleJSONAPI框架的优缺点阐述
优点：
* Gazelle原生API，对于支持此API的网站，无需做过多的配置就能轻松适配
* 基于JSON解析的代码相对html格式简单清晰
缺点：
* 原生格式仅对音乐站点支持较好例如RED/DIC，对于一些轻微改版的网站支持一般，例如UHD，缺失一定信息
* 许多基于Gazelle早期版本的网站，或者Gazelle fork版本的网站都不支持此API

feat:新增GazelleJSONAPI框架，并适配DIC和RED

---

resource/sites/jpopsuki.eu/getSearchResult.js
resource/sites/nebulance.io/getSearchResult.js

- fix: 优化Nebulance和JpopSuki搜索结果中标题显示
- 将Neblance标题显示调整为种子文件/文件夹标题，原group标题不能反映文件信息；
- 如种子含有评论，JpopSuki原返回标题末尾会带有如(2)的标记，此为评论数，已调整去除。

优化NBL/JpopSuki搜索结果中标题显示

---

resource/sites/pt.hdupt.com/config.json

其实并不需要修改filters，原来出现问题的原因目测是匹配了两个selector（大概，我并没有捐赠魔力所以并没法复现），所以只要把selector修改一下就ok了
Closes #330

fix: 修复 HDU 魔力值获取异常的Bug

---

resource/sites/ptsbao.club/config.json
resource/sites/springsunday.net/config.json
resource/sites/www.torrentleech.org/getUserSeedingTorrents.js

tl:https://github.com/ronggang/PT-Plugin-Plus/issues/314
烧包更改了新信息的调幅颜色为indigo，导致匹配失败
SSD没有外层的t导致匹配失败

fix: 站点烧包、SSD新信息获取以及tl做种体积的调整

---

resource/sites/pt.keepfrds.com/config.json

出问题就怪musk
目前做种信息inactive就不显示了，所以获取到就显示下载中，不过进度条大概15分钟才能跟上实际进度？所以肯定是不准的。
进度
* ~~朋友~~
* 南洋
* 猫站
* * 萌猫
* 影客
* 搞清洁
* ~~HDC下载未活动显示为活动~~
* pth

朋友 增加获取做种信息

---

resource/schemas/NexusPHP/getSearchResult.js

fix:修正葡萄的种子发布时间
之前葡萄的发布时间显示为"xx天xx小时"，现在通过粗略计算转换成与其他站点一致的时间显示。方便排序。

fix:修正葡萄的种子发布时间

---

resource/schemas/NexusPHP/getSearchResult.js

fix:葡萄种子上传时间在两种模式下都能用。
之前我并不清楚葡萄的网站设置可以调整上传时间的显示方式。
上一个pr
https://github.com/ronggang/PT-Plugin-Plus/pull/499#issue-406418160
会造成已经设置了葡萄的网站时间显示类型为发生时间的用户出现解析错误的情况，现修正。
设置'发生时间'解析出的时间更精确。要么revert掉上一个pr，要么加上现在这个，保证两种网站设置不冲突。

fix:葡萄种子上传时间在两种模式下都能用

---

resource/schemas/UNIT3D/getSearchResult.js

Unit3D 使用中文的话，会显示类似1天前，但是1 day ago能自动转换为时间格式
所以就将中文替换为英文。
并且在搜索界面站点不会提供详细的发布时间，以前的资源发布时间精度差距就较大，故超过1周的资源就不进行转换。
该commit不影响英文界面，因此英文界面应该是所有都会显示成时间格式
(漏了个秒，等会更新下

Unit3D 中文显示时间调整

---

resource/sites/pt.hd4fans.org/config.json

由于HD4FANS的置顶种使用了twoupfree_bg，因此所有置顶种都会被错误的标记为2xFree，因此在torrentTagSelectors中将此class去除。不过这也引发了设置为高亮显示时2xFree无效的情况，其实最好的解决方法还是联系站点修改class了（笑

fix(HD4FANS): 修复错误的标记2xFree的问题，完善搜索入口和进度条

---

resource/schemas/Common/torrents.js
resource/sites/concertos.live/config.json

由于Concertos本身种子页面不提供下载，因此由脚本生成，更改了模板架构已便于直接获取连接

feat: 新增Concertos

---

resource/sites/totheglory.im/details.js

有一些扩展会为链接添加class，导致选择器失效，因此使用正则来获取链接
例如[Online Download Manager](https://chrome.google.com/webstore/detail/online-download-manager/opjjpmhoiojifppkkcdabiobhakljdgm)会为链接添加 `class="md-opjjpmhoiojifppkkcdabiobhakljdgm_doc"`

perf(TTG): 优化获取下载链接

---

resource/sites/hdfans.org/config.json
resource/sites/pt.msg.vg/config.json
resource/sites/pt.soulvoice.club/config.json

新增：
- PTMSG的完整进度条
- HDFans/Soulvoice未提供做种状态，无法判断已完成种子是否在做种中，故添加了部分进度条功能，已完成种子统一显示“已完成，未做种”

[Feature] - Add progress bar for HDFans/PTSMG/Soulvoice

---

resource/sites/leaguehd.com/config.json
resource/sites/leaguehd.com/getSearchResult.js

- fix: 修补
因LeagueHD 最近进行重大改版，PTPP 的搜索功能，批量发送功能不兼容。保种数据因站点压力只提供100个最新种子数据，无法正确展示。
跟LeagueHD 管理沟通后，提供了保种数据接口，于是我将这三个bug 一起修复了。注：PTPP 搜索功能代码为 [#636](https://github.com/ronggang/PT-Plugin-Plus/pull/636) @enigmazack 大佬的代码，万分感谢。
柠檬是个不满一年的新站，希望大佬垂青支持。

FIx: Patch-LeagueHD-Fix

---

resource/sites/leaguehd.com/config.json

- fix: 修补 bug
柠檬底层大改后，已适配完成搜索，批量发送，保种数据错误。
经用户测试，种子详情页工作不正常，分析为原种子详情页面为 `url/details.php` ，改版后为`url/details_大分类.php`
修改适配后，问题已解决。
望大佬merge 修改。感谢感谢

Fix: 适配LeagueHD 改版后种子详情页面ptpp工作问题

---

resource/sites/leaguehd.com/config.json

- fix: 修补 bug
本次更新为用户使用中反馈新问题修复。
1. 修复使用豆瓣api 返回数据无法搜索问题
2. 修复最新种子页面无侧边栏
经chrome firefox edge 测试功能正常。
望大佬merge 修改。感谢感谢

Fix: LeagueHD 修复豆瓣，imdb 搜索失效，最新种子页面无侧边栏

---

resource/sites/lemonhd.org/config.json

- fix: 适配柠檬改版
本次pr 为用户反馈柠檬电影，经测试发现为柠檬电影改版，电影分类搜索返回页变更。
修改返回页为全站搜索返回页后修复。
经chrome firefox edge 测试功能正常。
望大佬merge 修改。感谢感谢

Fix: 修复柠檬电影改版无法搜索问题

---

README.md

Link broken reasons were not clear to new users.

docs: add additional info on broken chrome/firefox webstore links

---

resource/schemas/NexusPHP/common.js
resource/schemas/NexusPHP/details.js

某些站点的种子文件下载地址并不使用 `passkey` 作为鉴权，而是使用一次性哈希，如 pthome 使用 `downhash`，HDC 使用 `hash`

feat: support sites with hash/downhash instead of passkey

---

.github/workflows/dev_build.yml

- 之前: 所以PR只会checkout dev分支
- 现在: 所有PR会checkout PR自己的分支, 这样普通用户就能直接在PR里面下载测试

更新Github Action

---

resource/sites/lemonhd.org/config.json

- fix: 防止分类搜索变动，导致需要经常修改
其实两个月前已切换为全站搜索，今天全站搜索又有变动导致无法搜索无法返回结果。已与柠檬开发确认比次变动已固定，长时间不会变动。
经chrome firefox edge 测试功能正常。
望大佬merge 修改。感谢感谢

Fix: 修复柠檬搜索，切换到全站搜索

---

src/options/views/statisticCharts/SiteBase.vue

图标统计分享是生成png图片, 中间的空隙就是透明背景, 当把png发送到黑色背景的地方时候, 中间的缝隙也变成了黑色, 特别难看。

fix: 取消图表间空隙

---

resource/sites/snakepop.art/config.json
resource/sites/snakepop.art/getUserSeedingTorrents.js

`ADD Site: Snakepop`
- feat: 适配做种体积计算翻页，修复用户等级乱码
- 与GazelleJSONAPI 最主要的改动为第43行，屏蔽了返回中文为数字编码(如上图)，保留英文等级。
- 为防止翻页导致体积统计不准确，增加了getUserSeedingTorrents.js

ADD Site: Snakepop.art

---

resource/sites/jptv.club/config.json

Adding JPTV support.
This site has been created for 1+ year and has 20k+ torrents at the moment.

feat: add site support for JPTV.club

---

resource/sites/sugoimusic.me/config.json

Adding site support for SugoiMusic.
SugoiMusic is a music tracker built by jpop staff. It has 3.5k users and 102k torrents.
The commit has been tested locally:
Note:
- the bonus system in this tracker is called "Sugoi"
- the seeding size can only be fetched in user.php

feat: add site support for SugoiMusic

---

resource/sites/greatposterwall.com/config.json

GPW is a movie tracker created by DIC team. The site just started internal registrations this month but it already had ~3k torrents.
The commit has been tested locally on Edge:

feat. add site support for GPW (GreatPosterWall)

---

resource/sites/beyond-hd.me/config.json

- 之前: 所有消息都会提醒, 包括Bets, 很烦
- 现在: 只有Private Messages会提醒

fix: BHD消息提醒不包括bets

---

src/options/views/statisticCharts/SiteBase.vue
src/service/filters.ts

fix: BarChart负值显示

---

resource/i18n/en.json
resource/i18n/zh-CN.json
src/interface/common.ts
src/options/views/Home.vue
src/options/views/settings/Sites/Editor.vue

Fix #841, 已添加站点里面没有`messageCountToggle: true`值, 导致升级之后所有站点都不显示消息提醒了.

fix: disable message count display

---

resource/sites/lemonhd.org/config.json
resource/sites/lemonhd.org/getSearchResult.js

修复了柠檬站点副标题不显示的问题
添加了柠檬站点的限时免费标签的显示
修复了柠檬站点做种状态的显示

fix: #713 柠檬副标题做种状态free标签问题

---

resource/sites/hdroute.org/config.json
resource/sites/hdroute.org/getSearchResult.js
resource/sites/passthepopcorn.me/config.json
resource/sites/passthepopcorn.me/getSearchResult.js
resource/sites/passthepopcorn.me/getUserSeedingTorrents.js
resource/sites/uhdbits.org/config.json
resource/sites/uhdbits.org/getSearchResult.js
resource/sites/uhdbits.org/getUserSeedingTorrents.js
src/interface/common.ts
src/options/views/search/SearchTorrent.ts

https://github.com/ronggang/PT-Plugin-Plus/projects/1#card-21167843
这次是根据功能计划里面的2.0修改的。
主要改动:
`UserInfo` 接口加了一个 `seedingList`，记录做种信息
`SearchResultItem` 接口加了一个 `id`，方便标记
对应站点在 `config` 文件中 `userSeedingTorrents.fields.seedingList` 中设置做种列表的解析方法（部分站点可能要新开一种不同于`userSeedingTorrents`的方法来解析）
对应搜索结果解析的时候加上种子 `id` 的信息
UI 界面添加检查种子`id` 是否在 `seedingList` 来决定是否显示做种的逻辑
预期效果：
获取站点信息的同时，获取做种列表
搜索结果根据做种列表标记做种中的种子
目前某R的修改效果已经达到，有没有其他bug待测试。

feat: 添加某R做种信息

---

resource/sites/club.hares.top/config.json

增加了对白兔俱乐部（HaresClub）站点的支持。
通用schema无法显示白兔俱乐部的奶糖数，网站plugin也显示异常。新增selector和plugin之后可以正常显示。
测试了“添加站点”/“我的数据”/搜索以及站内plugin，均正常工作。
白兔俱乐部（HaresClub）是主打全4k影视的pt站。详细信息可参考网站主页 https://club.hares.top

feat: add HaresClub support

---

resource/sites/www.pttime.org/config.json

- fix #954: error count for seeding (still error for seeding size)
将做种数(seeding)替换为首页`当前活动`所显示的数字以避免个人信息页只显示20条信息所造成的计数错误
**但由于无法通过其他方式获得具体的大小，做种体积(seedingsize)仍受个人信息页限制（只显示20条），需网站维护者解决。**

fix(pttime): error count for seeding (still error for seeding size)

---

public/manifest.json

Open Firefox, open https://fonts.google.com/icons?selected=Material+Icons, the page is broken, caused by PT Plugin Plus

fix: google fonts page broken in Firefox

---

resource/sites/lemonhd.org/getSearchResult.js

没有相关结果时，LemonHD和其它使用NexusPHP架构的网站不同，还是会列出表头，后续脚本读取种子列表出错，导致误报连接出错

fix:修复 LemonHD搜索没有相关种子时，误报错误

---

resource/i18n/zh-CN.json
src/options/views/settings/Base/Index.vue

取消常规设置必须选择默认下载服务器才能保存数据的限制

---

src/options/views/search/SearchTorrent.vue

feat: 搜索结果副标题增加 title 属性以便查看全部

---

resource/sites/cinemageddon.net/getSearchResult.js

- fix: 修复CG中文搜索时返回不相关结果的bug
当搜索中文字符时，CG默认回到browse页，导致结果提取器错误提取全部browse页种子。特征为browse页翻页href中缺少`search`。
注：代码开头加入了getQueryString，原本是打算通过page的值来判断的，没有采用，忘了删，懒得重新提交了，留着也不碍事。

修复CG中文搜索时返回不相关结果的bug

---

src/options/components/SearchBox.vue
src/options/views/Home.vue
src/options/views/search/SearchTorrent.vue

修改了头部搜索框/我的数据搜索框/搜索结果过滤输入框在手机上输入法回车键的表现, 默认现在是 `next` (切换到下一个, 相当于 `tab`), 现在修正为 `search`.
未修复前按回车按钮会切换到下一个输入框, 现在按回车可以直接搜索.
PS: 没修复的话, 需要切换非标准输入法, 然后点回车后再切换标准输入法.

fix: 搜索框手机端回车按钮修改为搜索

---

resource/sites/www.haidan.video/config.json

-------
海胆的等级积分有千位分隔符，直接使用 parseInt 转换会丢失位数

fix(haidan): 修复读取等级积分带分号时识别错误的问题

---

resource/schemas/NexusPHP/config.json

-------
发现 firefox 下读取不到 ssd 的入站时间，调试发现 firefox 下读取到的时间字符串比 chrome 的多一个空白行，尝试用 trim() 处理后正常。

fix(nexusphp): 修复 firefox 下部分站点解析不到入站日期的问题

---

resource/sites/u2.dmhy.org/config.json

-------
目前获取时魔取的是魔力详情页面表格第一行的数据，是最近一次计算获得的15分钟内所获魔力值，并不是平均时魔。
应以该页面下部的24小时总魔力求平均时魔。

fix(u2): 修复获取时魔不正确的问题

---

resource/sites/gay-torrents.org/config.json
resource/sites/gay-torrents.org/getSearchResult.js
resource/sites/www.gaytor.rent/config.json
resource/sites/www.gaytor.rent/getSearchResult.js

支持新站点。默认搜索模式（`misc`）不包括 NSFW 内容，以期符合默认全局搜索的需要。
* [GTru](https://www.gaytor.rent/)，新近由[旧域名](https://www.gaytorrent.ru/)迁移
* Closes #664
* [GTorg](https://gay-torrents.org/)，并有[备用域名](https://gay-torrents.se/)
* 相关 #202

feat:新增GT适配

---

resource/i18n/en.json
resource/i18n/zh-CN.json
resource/sites/tjupt.org/config.json
src/background/user.ts
src/interface/common.ts
src/options/views/Home.vue

增加北洋园(tjupt)的升级条件。
修改的内容：
1. LevelRequirement和UserInfo添加了完成种子数（downloads）和累计做种时间（seedingTime）这两个属性
2. 这两项信息通过页面`/classes.php`获取，参考PR  #1290 的做法添加了levelExtendInfo选择器
3. 修改`Home.vue`中的formatUserInfo和calculateNextLeve方法，通过比较名称实现对当前等级的判断
需要注意的内容：
* 升级条件中的H&R积分要求忽略
* 需要检查第三项修改是否对其它内容造成影响

feat(tjupt):增加升级条件

---

resource/clients/synologyDownloadStation/init.js
src/background/controller.ts

挺老的一个issue了，一直还没解决。 关联issue：https://github.com/pt-plugins/PT-Plugin-Plus/issues/618
看了下现有过程，现在创建下载任务时调用的获取种子文件的方法没有直接返回种子对象本身（种子经过parse后拿到的结构化数据，以下都称之为torrent），只有content（种子的file blob，以下都称之为content）。
遂从后端入手，获取种子的方法在`src/background/controller.ts#881` ，该方法其实是有解析种子的参数，但如果将该参数置为true则不会返回种子的content（鱼和熊掌不可兼得是吧）
于是决定扩展该方法，考虑到方法较为底层，所以改动的思路是影响范围尽可能小。于是分析该方法的过程中发现，如果入参`parseTorrent`为`false`时，resolve出去的则直接是content，没有经过任何对象的封装，如果需要追加返回torrent的话，势必改变出参的数据类型，这样改动影响范围太大，风险不可控。
而`parseTorrent`为`true`时，resove出去的数据经过对象封装，扩展字段很轻松，然后决定就干它了
根据调用链判断，该参数只被用在了`src/options/views/search/KeepUpload.vue#465`的`getTorrent`方法，查看上下文判断是辅种的搜索功能？辅种功能没用过，不能对改动进行测试，但考虑到仅仅在出参的对象中新增了一个key，应当不属于breakchange
新建的下载任务被附加了真实的filename，DownloadStation也可以正常查看
感觉项目有点久了，很多实现和方法都很emmmmmm，维护起来确实有一些难度了 …

fix: 将传给Synology DownloadStation的下载任务附带正确的种子文件名

---

resource/sites/lztr.me/config.json

- 增加了升级条件，需要获取发布数和下载数
- 为 lztr 增加了新的 `selector`: `levelExtendInfo`, 其中包含了做种数、发布数、下载数

feat(lztr): 增加升级条件

---

resource/sites/jpopsuki.eu/config.json

- collaborator 添加历史贡献者
- `userExtendInfo` 添加发布数和下载数
- 增加了升级条件（需要用到发布数）

feat(jpopsuki): 增加升级条件

---

resource/i18n/en.json
resource/i18n/zh-CN.json
resource/schemas/GazelleJSONAPI/config.json
resource/sites/dicmusic.club/config.json
src/interface/common.ts
src/options/views/Home.vue

海豚的升级条件包含“独特分组”和“完美FLAC”两个数据，其中“独特分组”应该是 GazelleJSONAPI 站都有的数据，“完美FLAC”是音乐站有的数据。
- 在相关的代码中增加了“独特分组(uniqueGroups)”和“完美FLAC(perfectFLAC)”，参考了 #1318 的代码
- 增加了“独特分组(uniqueGroups)”、“发布数(uploads)”和“下载数(downloads)”的获取
- 增加了“完美FLAC(perfectFLAC)”的获取
- 增加了升级条件
海豚用户等级中，这两个级别的要求几乎一样，只是 Elite Torrent Master 对于“完美FLAC”的数量可以包含 WAV 和 DSD 格式，而 Elite Torrent Master Plus 只能是 FLAC 格式，但出于以下几点，在代码里的要求是完全一样的：
1. API 无法简单获取 WAV 和 DSD 数量
2. 站点鼓励 FLAC，WAV 不再记入“完美”
3. DSD 格式实际数量相当少，全站只有几十个
因此对于大多数用户，这两个级别的升级条件可以认为是相同的

feat(dicmusic): 增加升级条件

---

resource/sites/springsunday.net/config.json

fix(SSD): 搜索结果副标题匹配 #1350

---

src/options/views/search/SearchTorrent.scss

Make dark theme text white on black, and purple when hovered.

fix: Update anchor style for dark theme

---

resource/sites/nextpt.net/config.json

* 修复 FSM 以下内容的获取: 用户名, 上传量, 下载量, 做种数量, 保种时G
[dist.zip](https://github.com/pt-plugins/PT-Plugin-Plus/files/11323111/dist.zip)

fix(FSM): 用户名, 上传量, 下载量, 做种数量, 保种时G

---

resource/clients/qbittorrent/init.js
resource/clients/transmission/init.js
resource/i18n/en.json
resource/i18n/zh-CN.json
src/background/controller.ts
src/interface/common.ts
src/options/views/settings/Sites/Editor.vue

* 添加种子时, 按站点设置自动限速
* 因为时间有限且tr适配方式和 qb 应该差不多，所以目前只适配了 QB
https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-(qBittorrent-4.1)#add-new-torrent
https://github.com/transmission/transmission/blob/main/docs/rpc-spec.md#32-torrent-mutator-torrent-set
https://github.com/pt-plugins/PT-Plugin-Plus/wiki/developer
* 限速设置可以在站点界面添加(已测试) 也可以在 site 的 config.json 中预设.(未测试)
#1421 #145 #317 #1030
> ~~自己 PR 就什么都有了~~

feat: 添加种子时, 按站点设置自动限速

---

resource/sites/leaves.red/config.json

红叶用户名后面有一个枫叶图标会在PTPP中被识别成一个特殊字符。

fix(红叶): 忽略红叶用户名最后的枫叶图标

---

resource/sites/ncore.pro/config.json
resource/sites/passthepopcorn.me/config.json

- feat: 增加nCore的数据显示
简单添加了这个站数据 包括名字等级上传魔力入站时间等数据，ratioless没有下载
但搜索、种子推送还有待支持

feat: add new tracker nCore

---

resource/sites/dicmusic.com/config.json

该站域名由 dicmusic.club 永久变更为 dicmusic.com
另见#648，可能有统计信息丢失的问题

fix: site domain changed: dicmusic.club -> dicmusic.com

---

src/options/views/Home.vue

本地调试as number并没有把level转换为number，依然在用字符串判断，导致ttg这种level大于10的判断错误

Fix: levelRequirement.level部分站点为字符串，未转换为数字导致站点状态判断错误

---

resource/clients/deluge/config.json
resource/clients/flood/config.json
resource/clients/qbittorrent/config.json
resource/clients/ruTorrent/config.json
resource/clients/synologyDownloadStation/config.json
resource/clients/transmission/config.json
resource/clients/utorrent/config.json
resource/i18n/en.json
resource/i18n/zh-CN.json
resource/schemas/Common/common.js
resource/schemas/NexusPHP/common.js
resource/schemas/TNode/common.js
src/background/contextMenus.ts
src/interface/common.ts
src/options/views/settings/DownloadClients/Add.vue
src/options/views/settings/DownloadClients/Editor.vue
src/options/views/settings/DownloadClients/Index.vue

* 所有类型下载客户端都支持禁用
----
* 下载服务器配置
> 编辑后需要刷新  
* 下载服务器编辑
* 种子页
* 种子详情页
* 右键菜单未过滤禁用的下载客户端
> 没找到对应代码，且使用频率相对较低，先算了。欢迎告知或者直接PR

feat(#974): 支持禁用部分下载客户端

---

resource/i18n/en.json
resource/i18n/zh-CN.json
src/interface/common.ts
src/options/views/Home.vue
src/options/views/UserDataTimeline.vue
src/options/views/settings/Sites/Editor.vue

[#536](https://github.com/pt-plugins/PT-Plugin-Plus/issues/536#issuecomment-647529898) #527 
> 根据群友反馈，去掉了 2FA， 增加了 收件箱 的入口。  
> 收件箱入口 可以配合 PTPP 默认的消息提醒使用。~~每次打开小红点页面也挺麻烦的不是？~~   
* 直达控制面板，调整个人设置，复制 passkey
* 直达用户详情
* 管理可以只定义如申诉页，种审页，论坛特定板块
> 这个和用户等级一样。 鼠标 hover 才会显示出来。默认不显示，可以在站点设置中调整。  
* [pter 快捷链接](https://github.com/IITII/nexusphp_forums#pter-%E5%BF%AB%E6%8D%B7%E9%93%BE%E6%8E%A5)
* [greasyfork](https://greasyfork.org/zh-CN/scripts/467909-pter-%E5%BF%AB%E6%8D%B7%E9%93%BE%E6%8E%A5)

feat(#536): 为每个站点增加一个入口页面列表

---

src/options/views/Home.vue

#1260 
* 至于字段目前的对齐方式，我觉得挺不错的。数值之类的右对齐没问题，先不说设计，数值有长有短。居中肯定不行，左对齐也不行，只能右对齐。 ~~不信可以自己改改试试，改 align 值即可~~
https://github.com/pt-plugins/PT-Plugin-Plus/blob/91a2575b839cd64f3336552838314bcbdd1107fb/src/options/views/Home.vue#L309-L372
* 更新前
* 更新后

fix(#1260): 对齐数据更新时间

---

resource/clients/deluge/init.js
src/options/views/settings/Sites/Editor.vue

#145
* [废弃] 从 linuxserver.io 的 docker 镜像来看，rtorrent 和 flood 已经很久没更新了。主观感觉上使用的人也很少，不再单独适配。
* [搁置] utorrent 只能再种子添加后限速，且添加成功时不会返回种子 hash（类似于种子 id，调用限速接口需要。
```
请求网址: http://xxx:8082/gui/?token=xxx&action=setprops&s=ulrate&v=10240&hash=E64BE295746E79657138B71926342B43BB01C9C0
请求方法: GET
```

feat: deluge 限速支持

---

resource/sites/htpt.cc/config.json

fix: 海棠双份按钮

---

src/options/views/Home.vue

#1506
* VIP 不显示升级条件，hover还是可以正常看到目前符合哪一个等级的要求
* 对不同的用户组（VIP，管理，普通用户）显示不同的 done 按钮
* 按通用名称进行了简单的用户分组
* 管理：admin,moderator,sys,retire,管理,版主,发种,保种,上传,退休
* VIP：vip,贵宾
* 预设 icon 从左到右：普通用户，管理，VIP

fix: 调整用户级别显示

---

dev.md
resource/i18n/en.json
resource/i18n/zh-CN.json
src/interface/common.ts
src/options/components/SearchBox.vue
src/options/views/search/SearchTorrent.ts
src/options/views/settings/Base/Index.vue

https://github.com/pt-plugins/PT-Plugin-Plus/issues/257
https://github.com/pt-plugins/PT-Plugin-Plus/pull/1508

fix: 调整搜索方案默认搜索逻辑, 可在 通用配置-搜索 中调整

---

src/options/components/SearchBox.vue

* 超出 70% 屏幕高度后可滚动
* 隐藏滚动条
* Chrome 测试通过

fix: 搜索方案滚动

---

src/options/components/SearchBox.vue
src/options/plugins/EventBus.ts
src/options/views/search/SearchTorrent.ts

* 相同 key 跳过路由跳转, 应该使用 this.$route.params.key 进行判定
* 跳过的路由跳转, 使用 EventBus 触发搜索
https://github.com/pt-plugins/PT-Plugin-Plus/issues/257
https://github.com/pt-plugins/PT-Plugin-Plus/pull/1508
https://github.com/pt-plugins/PT-Plugin-Plus/pull/1561
@Meng-Lan

ref: 使用 EventBus 触发搜索

---

resource/i18n/en.json
resource/i18n/zh-CN.json
src/options/views/Home.vue

将首页的 最后一次数据更新时间 修改为相对时间，绝对时间放置到 title 里面
before
after

feat(Home):  Change the ` lastUpdateTime` format to relative time.

---

resource/i18n/en.json
resource/i18n/zh-CN.json
src/options/views/search/SearchTorrent.scss
src/options/views/search/SearchTorrent.ts
src/options/views/search/SearchTorrent.vue

feat:搜索结果页面可选择标题中间省略

---

src/options/views/UserDataTimeline.vue

通过分析[dom-to-image](https://github.com/tsayen/dom-to-image)库源码，发现对[失败图片](https://github.com/tsayen/dom-to-image/blob/master/src/dom-to-image.js#L496)的处理逻辑中有个`imagePlaceholder`属性至关重要，如果没有设置将会**直接报错**，所以只需要设置一个默认图片就可以完美解决**如果图片获取失败就一直转圈的问题**

fix:时间轴错误图片处理优化

---

resource/i18n/en.json
resource/i18n/zh-CN.json
src/background/config.ts
src/interface/common.ts
src/interface/enum.ts
src/options/views/Home.vue
src/options/views/search/SearchTorrent.vue
src/options/views/settings/Base/Index.vue
src/options/views/settings/Sites/Editor.vue

* 从站点设置里面读取标签作为分组依据
* 设置优先级后, 标签顺序和站点默认排序按优先级从小到大
----
* `刷新我的数据`按钮已修改为 `刷新当前分组的数据`. 可以在处理完已读消息之后一键刷新
* 未选择分组, 或选择全部将返回所有站点
* 标签之间的关系是 **或**
* 联动 时间轴 页面
* 调整下拉框高度
* 调整`打开刷新错误网站`和`打开未读消息`按钮的表现形式. 目前保留是为了提醒用户需要进一步处理
* 更新站点 config.json 的标签.
* 默认不选择标签的情况下, 会有样式问题,,, ~~选个所有就好了~~

feat: 支持站点分组

---

resource/sites/ptvicomo.net/config.json

fix(ptvicomo):象站魔力修改为象草

---

resource/publicSites/douban.com/top250.js

#1631 
在Top 250 页面点击后，用电影名称的方式搜索

Fix: 修复豆瓣Top 250页面无法搜索的问题

---

resource/clients/qbittorrent/init.js
resource/i18n/en.json
resource/i18n/zh-CN.json

打开”发送种子时自动添加QB分类功能“，在没有选择保存路径时无法定义分类名称，比如使用”一键下载“功能的时候。
这个patch允许使用类似下面的分类列表格式
```
默认分类,_
```
如果发送种子时没有指定保存路径将使用该行定义的分类名。

feat: use _ to indicate default savePath

---

resource/sites/ptvicomo.net/config.json

fix(ptvicomo):修复象站石墨显示

---

resource/schemas/UNIT3D/config.json
resource/sites/anthelion.me/getSearchResult.js

fix(unit3d): torrent tag
feat(ant): support IMDB search

fix(unit3d), feat(ant)

---

resource/sites/byr.pt/config.json

解决了关于BYRBT站的两个问题：
1、更新了不同等级拥有的权限内容。包括升级赠送邀请数量、购买/发送邀请等级和购买昵称特效等等。
2、新增了正确获取BYRBT用户信息的代码。原先提交了issue，原来代码上传/下载/发布数据和注册日期等获取错乱，时魔数据符合网站，经网站论坛用户wireshark抓包，并批评网站首页的信息调查发现原来的代码是从首页index.php获取用户信息，新的昵称特效功能导致插件获取到了目前购买第一个竞价置顶的用户的信息，所以所有用户才会获取到错误的信息。
Two fixes about PTPP issues #1682 related to BYRBT:
1. Update level requirements level info: permissions owned by different levels (including invitation numbers given during upgrade, level required to buy/send an invitation and qualification to purchase nickname effects, etc.)
2. Add codes to get correct user info from BYRBT. I have sent an issue #1682 , as user information obtained by PTPP is incorrect, including upload/download size, uploaded torrents numbers and so on excpet points per hour. An enthusiastic user from our fourm reminded that the …

fix(BYR): Level Requirements and userBaseInfo Getting

---

resource/clients/qbittorrent/init.js
resource/i18n/en.json
resource/i18n/zh-CN.json
src/background/controller.ts
src/interface/common.ts
src/options/views/settings/DownloadClients/Editor.vue

#1621
* 支持将 站点名称添加为 qb 标签
> 以 frds 为例, 小写 host 是 `keepfrds`, 小写站点名是 `pt@keepfrds`
* qb 4.6.1 webui 已经支持按 tracker host 对种子进行筛选, 没有手动打站点 tag 的必要
* 目前大站都支持 qb 4.6.1, 建议直接升级
* 而且 iyuu 辅种也不会打 tag, 但是有第三方脚本, 按需选择. https://github.com/pt-plugins/PT-Plugin-Plus/issues/1621#issuecomment-1769516259

feat: 可将站点名称作为 tag 添加到 qb

---

resource/sites/u2.dmhy.org/config.json

p.s. 根据 #515，测试了当下载量为 0 且语言不是简体中文时，此问题复现。
参考其它站点的配置文件，试着定义了一下选择器，本地测试了一下可以解决问题。

fix(u2): 修复非简体中文语言环境下上传量和下载量获取的问题

---

resource/sites/byr.pt/config.json

修复了在 BYR 种子详情页点击“复制链接”按钮后，写入到剪切板的 URL 不含有 passkey 参数的问题。
已本地测试通过：
暂未发现对其他功能造成影响。

fix(BYR): 种子详情页"复制链接"不带passkey

---

resource/sites/kp.m-team.cc/config.json

补充 帳號保留規則 (Account Parking , Keeping Rules)
帳號保留規則 (Account Parking , Keeping Rules)
沒有流量的用戶（即上傳/下載資料都為0）在註冊 5 天後將被刪除帳號；
未封存帳號的用戶連續 40 天不登錄將被刪除帳號(已經刪除的帳號是不可能用任何手段恢復的，請自己設法重新註冊，以此為理由要求站方發邀請碼是不可能被接受的。“登錄”指訪問pt網站網頁並進行登入，單純做種不算登錄)；
封存帳號的用戶連續90 天不登錄將被刪除帳號；
府丞/Veteran User及以上等級用戶封存帳號（在控制面板）後不會被刪除帳號；
府尹/Extreme User及以上等級用戶會永遠保留。
按账号保留规则补充升级后福利

feat(m-team): 补充账号保留规则

---

resource/sites/cyanbug.net/config.json
resource/sites/ecustpt.eu.org/config.json

修复时魔的获取。
原站点配置文件的 selector 获取的是基础时魔，未考虑加成。故删除具体站点配置文件中的选择器，回退到 NP 架构的通用选择器（`#outer td[rowspan]`），即可正确获取。
已在本地测试。

fix(ecustpt&cyanbug): bonusPerHour

---

resource/sites/byr.pt/config.json

fix(byrpt): messageCount

---

resource/i18n/en.json
resource/i18n/zh-CN.json
resource/sites/fsm.name/config.json
src/background/user.ts
src/interface/common.ts
src/options/views/settings/Sites/Editor.vue

* 支持在站点设置里面设置 token
* fsm token 过期太快，测试太麻烦, 先不做了。从截图里面可以看到用户数据是已经获取到了的
#1684

feat: 支持在站点设置里面设置 token (fsm)

---

resource/sites/piggo.me/config.json

适配站点，新增一个 selector。
猪站的界面不太一样，故使用 NP 架构的选择器匹配不到。
本地已测试，功能正常。

fix(pig): messageCount

---

resource/schemas/NexusPHP/config.json

这个错误不会影响前台，但会在background page中出现错误记录。
如图所示，当网页中不存在H&R信息时，选择器仍会返回一个Object，因此需要通过Object中的length属性判断是否有数据。

fix(nexusphp): 处理unsatisfieds(HnR)时在无数据时会抛出错误

---

resource/sites/discfan.net/config.json
resource/sites/pt.hd4fans.org/config.json

Get seedingSize in all 3 languages supported by the affected trackers. And this will fix #1739.

fix(discfan&hd4fans): seedingSize

---

resource/sites/audionews.org/config.json
resource/sites/digitalcore.club/config.json
resource/sites/login.superbits.org/config.json
resource/sites/losslessclub.com/config.json
resource/sites/www.trancetraffic.com/config.json

只做了获取用户信息、种子详情页发送到下载器、种子列表批量处理三个功能的适配。没有适配搜索功能。均已测试过能正常使用。
DCC与SBS使用的架构相同，均为rartracker，因为是前后端分离，种子详情页功能可能会出现插件运行早于api获取种子信息，导致获取到的种子体积为0的情况。考虑过要不要单独调用api获取种子体积，但感觉这么额外调用一次不太好，不知道有无较好的解决方案。
SBS的主域名是www.superbits.org，但目前访问会被强制跳转到login.superbits.org，除非手动将login.*的cookie复制到www.*上，否则正常是完全无法访问主域名的。因此我直接用了login.superbits.org作为主域名。

feat: add AN, DCC, SBS, LC, TT

---

resource/sites/fsm.name/config.json

feat: 修改api.fsm为fsm.xx/api,保证功能前提下允许从ptpp打开fsm网址
修复：修复上个版本造成​​无法下载种子的bug
1.将原本的api.fsm改为修改api.fsm为fsm.xx/api,保证功能前提下允许从ptpp打开fsm网址
2.修复上次提交在某些不该放token的位置放了token导致无法正常下载

修复FSM无法下载种子的bug同时修改启动网址允许从ptpp打开fsm网址而不是打开api.fsm

---

src/background/service.ts

修复火狐浏览器不支持extraHeaders的问题

---

resource/schemas/UNIT3D/config.json
resource/schemas/UNIT3D/getSearchResult.js
resource/sites/aither.cc/config.json
resource/sites/beyond-hd.me/getSearchResult.js
resource/sites/blutopia.cc/config.json

一堆各种站可能都需要测一下,可能有些之前可以（应该没有吧，我自己手头没几个站），改了后反而不行的。
想法还是以blu为基准。
理论用title判断是最好的，但是blu目前支持中文了，这块判断略微会有些长，所以还是用图标了。
另外只做了seeding和complete的判断，其他的判断成本有点高，有空在弄好了

feat(u3d): seeding status

---

resource/sites/xp.m-team.cc/getUserSeedingTorrents.js

https://github.com/pt-plugins/PT-Plugin-Plus/issues/1936
修复mt刷新数据失败。貌似mt给getUserTorrentList添加了一个强制的冷却。每2秒只能发送一个请求。除了等mt再给一个api以外，目前只能等这个2秒。

fix(mt): fix mt refresh rate limited

---

resource/sites/pt.gtk.pw/config.json
resource/sites/ubits.club/config.json
resource/sites/www.okpt.net/config.json

有些站的升级增量计算有误。下载数据被无条件满足。
原因是因为有些站的“downloaded”配置是“500G”这样，而不是“500GB”这样。`fileSizetoLength`函数负责把这个配置转换成一个以字节为单位的整数。而这个函数里有一个正则表达式是期待“GB”而不是“B”。导致了这些配置被转换成了0。从而被无条件满足。修改配置即可修复。（"T" vs "TB"同理）
用`find . -name "config.json" | xargs -n1 grep -r "G\""`和`find . -name "config.json" | xargs -n1 grep -r "T\""`找了所有错误配置，都改好了。
复现步骤：
1. 找一个配置错误的站。或手动去掉“B”。
2. 同时，下载量不能满足当前等级升级所需的下载量。
3. 但是下载量却显示已满足。
|Before|After|
| -------- | ------- |
|明明没有满足下载量，却认为我到了EU|正常计算下一级所需的下载增量|
|![CleanShot 2024-08-04 at 21 43 46@2x](https://github.com/user-attachments/assets/338bc372-e26e-44ec-a08e-e8bd73dc8095)|![CleanShot 2024-08-04 at 21 53 45@2x](https://github.com/user-attachments/assets/5c6c3f2d-a232-4695-83ff-c1b31da46580)|

fix: fix a few configs have incorrect "downloaded" with "G"/"T" instead of "GB"/"TB"

---

resource/sites/passthepopcorn.me/getSearchResult.js

为 PTP 搜索结果添加 `Free` 标签
注：由于将原有的 `crlf` 统一替换为了 `lf`，所以 diff 中看起来好像整个文件都重写了（

feat(PTP): add freeleech tag

---

resource/sites/ptvicomo.net/config.json

fix(ptvicomo): 修复搜索种子详情不显示

---

resource/sites/bitporn.eu/config.json

feat(bitporn): new site

---

resource/sites/fsm.name/config.json

详情页面只有一个下载按钮，可以与列表共用一个插件来实现推送种子，解决了需要手动设置 APICDN 的问题。

fix(fsm): send torrent in detail page

---

resource/sites/milkie.cc/config.json
resource/sites/milkie.cc/getSearchResult.js

感谢 https://github.com/pt-plugins/PT-Plugin-Plus/pull/1985#issuecomment-2326383497 的提醒，现在只需将 https://milkie.cc/settings/security 里获取的 API key 填入鉴权 Token 即可实现用户数据获取及搜索推送种子。

fix(milkie): auth with api key

---

resource/sites/tjupt.org/config.json

本PR修复以下问题：
编辑站点中指定搜索范围失效；
搜索方案中指定站点的搜索范围失效。
两者都会返回全部分类的结果。

fix(tjupt): 站点搜索范围功能失效

---

resource/sites/jpopsuki.eu/getSearchResult.js

当在 Profile 里关闭 torrent grouping 时，从搜索结果中获取种子报错。

fix(jpop): 当关闭 torrent grouping 时，从搜索结果中获取种子报错

---

resource/sites/hhanclub.top/getSearchResult.js

fix(hhanclub): remove "[新]" in title when getting search results

---

src/options/views/settings/Sites/Add.vue

在添加站点时，鼠标超过弹窗会自动关闭，这里使用简单的办法解决这个问题，并且保留原有交互
以下是效果预览
正常操作时候，一切正常
如果在操作中鼠标超出弹窗，会设置弹窗无法关闭
鼠标返回弹窗，即可恢复正常状态

fix:添加站点窗口自动关闭

---

resource/sites/lemonhd.club/config.json

feat: 站点【新柠檬】时魔、做种数量、做种体积的获取

---

resource/sites/piggo.me/config.json

fix: 更新猪猪等级规则中VU的下载量

---

resource/sites/nanyangpt.com/config.json

fix: 更新南洋等级

---

resource/sites/xingtan.one/config.json

fix: 更新杏坛等级

---

resource/sites/qingwapt.com/config.json

站点魔力公式展示形式改造，进行适配，并移除其余不需要的config配置
修复前：
修复后：

fix(qingwa): update bonusPerHour

---

resource/sites/monikadesign.uk/config.json

修复 monikadesign.uk 时魔数据显示为分钟魔的问题
修复后

fix: 修复 monikadesign.uk 时魔数据显示为分钟魔的问题
